<?php

namespace Database\Seeders;

use App\Models\Distrito;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DistritoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        Distrito::insert([
['name'=>'BAGUA','provincia_id'=>2],
['name'=>'IMAZA','provincia_id'=>2],
['name'=>'EL PARCO','provincia_id'=>2],
['name'=>'ARAMANGO','provincia_id'=>2],
['name'=>'COPALLIN','provincia_id'=>2],
['name'=>'LA PECA','provincia_id'=>2],
['name'=>'RECTA','provincia_id'=>3],
['name'=>'CHISQUILLA','provincia_id'=>3],
['name'=>'VALERA','provincia_id'=>3],
['name'=>'SAN CARLOS','provincia_id'=>3],
['name'=>'SHIPASBAMBA','provincia_id'=>3],
['name'=>'FLORIDA','provincia_id'=>3],
['name'=>'COROSHA','provincia_id'=>3],
['name'=>'CHURUJA','provincia_id'=>3],
['name'=>'JAZAN','provincia_id'=>3],
['name'=>'JUMBILLA','provincia_id'=>3],
['name'=>'CUISPES','provincia_id'=>3],
['name'=>'YAMBRASBAMBA','provincia_id'=>3],
['name'=>'SAN ISIDRO DE MAINO','provincia_id'=>1],
['name'=>'SAN FRANCISCO DE DAGUAS','provincia_id'=>1],
['name'=>'OLLEROS','provincia_id'=>1],
['name'=>'BALSAS','provincia_id'=>1],
['name'=>'LEIMEBAMBA','provincia_id'=>1],
['name'=>'MARISCAL CASTILLA','provincia_id'=>1],
['name'=>'MONTEVIDEO','provincia_id'=>1],
['name'=>'MAGDALENA','provincia_id'=>1],
['name'=>'SOLOCO','provincia_id'=>1],
['name'=>'CHETO','provincia_id'=>1],
['name'=>'SONCHE','provincia_id'=>1],
['name'=>'HUANCAS','provincia_id'=>1],
['name'=>'QUINJALCA','provincia_id'=>1],
['name'=>'ASUNCION','provincia_id'=>1],
['name'=>'CHUQUIBAMBA','provincia_id'=>1],
['name'=>'LA JALCA','provincia_id'=>1],
['name'=>'CHACHAPOYAS','provincia_id'=>1],
['name'=>'MOLINOPAMPA','provincia_id'=>1],
['name'=>'GRANADA','provincia_id'=>1],
['name'=>'CHILIQUIN','provincia_id'=>1],
['name'=>'LEVANTO','provincia_id'=>1],
['name'=>'RIO SANTIAGO','provincia_id'=>4],
['name'=>'NIEVA','provincia_id'=>4],
['name'=>'EL CENEPA','provincia_id'=>4],
['name'=>'SAN FRANCISCO DEL YESO','provincia_id'=>5],
['name'=>'TINGO','provincia_id'=>5],
['name'=>'CAMPORREDONDO','provincia_id'=>5],
['name'=>'LONYA CHICO','provincia_id'=>5],
['name'=>'LUYA','provincia_id'=>5],
['name'=>'LUYA VIEJO','provincia_id'=>5],
['name'=>'LONGUITA','provincia_id'=>5],
['name'=>'COLCAMAR','provincia_id'=>5],
['name'=>'PROVIDENCIA','provincia_id'=>5],
['name'=>'CONILA','provincia_id'=>5],
['name'=>'SANTA CATALINA','provincia_id'=>5],
['name'=>'SAN JERONIMO','provincia_id'=>5],
['name'=>'SANTO TOMAS','provincia_id'=>5],
['name'=>'COCABAMBA','provincia_id'=>5],
['name'=>'PISUQUIA','provincia_id'=>5],
['name'=>'SAN JUAN DE LOPECANCHA','provincia_id'=>5],
['name'=>'MARIA','provincia_id'=>5],
['name'=>'OCUMAL','provincia_id'=>5],
['name'=>'INGUILPATA','provincia_id'=>5],
['name'=>'TRITA','provincia_id'=>5],
['name'=>'OCALLI','provincia_id'=>5],
['name'=>'LAMUD','provincia_id'=>5],
['name'=>'SAN CRISTOBAL','provincia_id'=>5],
['name'=>'CHIRIMOTO','provincia_id'=>6],
['name'=>'MILPUC','provincia_id'=>6],
['name'=>'COCHAMAL','provincia_id'=>6],
['name'=>'LIMABAMBA','provincia_id'=>6],
['name'=>'HUAMBO','provincia_id'=>6],
['name'=>'SAN NICOLAS','provincia_id'=>6],
['name'=>'TOTORA','provincia_id'=>6],
['name'=>'VISTA ALEGRE','provincia_id'=>6],
['name'=>'LONGAR','provincia_id'=>6],
['name'=>'OMIA','provincia_id'=>6],
['name'=>'MARISCAL BENAVIDES','provincia_id'=>6],
['name'=>'SANTA ROSA','provincia_id'=>6],
['name'=>'CAJARURO','provincia_id'=>7],
['name'=>'JAMALCA','provincia_id'=>7],
['name'=>'CUMBA','provincia_id'=>7],
['name'=>'EL MILAGRO','provincia_id'=>7],
['name'=>'BAGUA GRANDE','provincia_id'=>7],
['name'=>'LONYA GRANDE','provincia_id'=>7],
['name'=>'YAMON','provincia_id'=>7],
['name'=>'SUCCHA','provincia_id'=>9],
['name'=>'LA MERCED','provincia_id'=>9],
['name'=>'CORIS','provincia_id'=>9],
['name'=>'HUACLLAN','provincia_id'=>9],
['name'=>'AIJA','provincia_id'=>9],
['name'=>'MIRGAS','provincia_id'=>10],
['name'=>'ACZO','provincia_id'=>10],
['name'=>'CHACCHO','provincia_id'=>10],
['name'=>'LLAMELLIN','provincia_id'=>10],
['name'=>'SAN JUAN DE RONTOY','provincia_id'=>10],
['name'=>'CHINGAS','provincia_id'=>10],
['name'=>'CHACAS','provincia_id'=>11],
['name'=>'ACOCHACA','provincia_id'=>11],
['name'=>'ABELARDO PARDO LEZAMETA','provincia_id'=>12],
['name'=>'COLQUIOC','provincia_id'=>12],
['name'=>'MANGAS','provincia_id'=>12],
['name'=>'CAJACAY','provincia_id'=>12],
['name'=>'CANIS','provincia_id'=>12],
['name'=>'TICLLOS','provincia_id'=>12],
['name'=>'AQUIA','provincia_id'=>12],
['name'=>'HUALLANCA','provincia_id'=>12],
['name'=>'HUAYLLACAYAN','provincia_id'=>12],
['name'=>'CHIQUIAN','provincia_id'=>12],
['name'=>'ANTONIO RAYMONDI','provincia_id'=>12],
['name'=>'LA PRIMAVERA','provincia_id'=>12],
['name'=>'PACLLON','provincia_id'=>12],
['name'=>'SAN MIGUEL DE CORPANQUI','provincia_id'=>12],
['name'=>'HUASTA','provincia_id'=>12],
['name'=>'CARHUAZ','provincia_id'=>13],
['name'=>'ATAQUERO','provincia_id'=>13],
['name'=>'MARCARA','provincia_id'=>13],
['name'=>'PARIAHUANCA','provincia_id'=>13],
['name'=>'SAN MIGUEL DE ACO','provincia_id'=>13],
['name'=>'SHILLA','provincia_id'=>13],
['name'=>'TINCO','provincia_id'=>13],
['name'=>'YUNGAR','provincia_id'=>13],
['name'=>'ACOPAMPA','provincia_id'=>13],
['name'=>'AMASHCA','provincia_id'=>13],
['name'=>'ANTA','provincia_id'=>13],
['name'=>'SAN NICOLAS','provincia_id'=>14],
['name'=>'SAN LUIS','provincia_id'=>14],
['name'=>'YAUYA','provincia_id'=>14],
['name'=>'CASMA','provincia_id'=>15],
['name'=>'BUENA VISTA ALTA','provincia_id'=>15],
['name'=>'YAUTAN','provincia_id'=>15],
['name'=>'COMANDANTE NOEL','provincia_id'=>15],
['name'=>'CORONGO','provincia_id'=>16],
['name'=>'YUPAN','provincia_id'=>16],
['name'=>'BAMBAS','provincia_id'=>16],
['name'=>'CUSCA','provincia_id'=>16],
['name'=>'LA PAMPA','provincia_id'=>16],
['name'=>'YANAC','provincia_id'=>16],
['name'=>'ACO','provincia_id'=>16],
['name'=>'INDEPENDENCIA','provincia_id'=>8],
['name'=>'COLCABAMBA','provincia_id'=>8],
['name'=>'HUARAZ','provincia_id'=>8],
['name'=>'HUANCHAY','provincia_id'=>8],
['name'=>'PARIACOTO','provincia_id'=>8],
['name'=>'TARICA','provincia_id'=>8],
['name'=>'LA LIBERTAD','provincia_id'=>8],
['name'=>'COCHABAMBA','provincia_id'=>8],
['name'=>'JANGAS','provincia_id'=>8],
['name'=>'OLLEROS','provincia_id'=>8],
['name'=>'PAMPAS GRANDE','provincia_id'=>8],
['name'=>'PIRA','provincia_id'=>8],
['name'=>'HUARI','provincia_id'=>17],
['name'=>'CHAVIN DE HUANTAR','provincia_id'=>17],
['name'=>'HUACACHI','provincia_id'=>17],
['name'=>'HUACCHIS','provincia_id'=>17],
['name'=>'HUACHIS','provincia_id'=>17],
['name'=>'RAPAYAN','provincia_id'=>17],
['name'=>'ANRA','provincia_id'=>17],
['name'=>'HUANTAR','provincia_id'=>17],
['name'=>'MASIN','provincia_id'=>17],
['name'=>'RAHUAPAMPA','provincia_id'=>17],
['name'=>'SAN MARCOS','provincia_id'=>17],
['name'=>'CAJAY','provincia_id'=>17],
['name'=>'PAUCAS','provincia_id'=>17],
['name'=>'PONTO','provincia_id'=>17],
['name'=>'SAN PEDRO DE CHANA','provincia_id'=>17],
['name'=>'UCO','provincia_id'=>17],
['name'=>'CULEBRAS','provincia_id'=>18],
['name'=>'HUAYAN','provincia_id'=>18],
['name'=>'COCHAPETI','provincia_id'=>18],
['name'=>'HUARMEY','provincia_id'=>18],
['name'=>'MALVAS','provincia_id'=>18],
['name'=>'YURACMARCA','provincia_id'=>19],
['name'=>'CARAZ','provincia_id'=>19],
['name'=>'PAMPAROMAS','provincia_id'=>19],
['name'=>'HUALLANCA','provincia_id'=>19],
['name'=>'HUATA','provincia_id'=>19],
['name'=>'MATO','provincia_id'=>19],
['name'=>'SANTA CRUZ','provincia_id'=>19],
['name'=>'SANTO TORIBIO','provincia_id'=>19],
['name'=>'PUEBLO LIBRE','provincia_id'=>19],
['name'=>'HUAYLAS','provincia_id'=>19],
['name'=>'CASCA','provincia_id'=>20],
['name'=>'LLAMA','provincia_id'=>20],
['name'=>'ELEAZAR GUZMAN BARRON','provincia_id'=>20],
['name'=>'LLUMPA','provincia_id'=>20],
['name'=>'LUCMA','provincia_id'=>20],
['name'=>'PISCOBAMBA','provincia_id'=>20],
['name'=>'FIDEL OLIVAS ESCUDERO','provincia_id'=>20],
['name'=>'MUSGA','provincia_id'=>20],
['name'=>'SAN PEDRO','provincia_id'=>21],
['name'=>'CONGAS','provincia_id'=>21],
['name'=>'COCHAS','provincia_id'=>21],
['name'=>'SANTIAGO DE CHILCAS','provincia_id'=>21],
['name'=>'OCROS','provincia_id'=>21],
['name'=>'ACAS','provincia_id'=>21],
['name'=>'CAJAMARQUILLA','provincia_id'=>21],
['name'=>'CARHUAPAMPA','provincia_id'=>21],
['name'=>'LLIPA','provincia_id'=>21],
['name'=>'SAN CRISTOBAL DE RAJAN','provincia_id'=>21],
['name'=>'PAMPAS','provincia_id'=>22],
['name'=>'SANTA ROSA','provincia_id'=>22],
['name'=>'BOLOGNESI','provincia_id'=>22],
['name'=>'HUACASCHUQUE','provincia_id'=>22],
['name'=>'LACABAMBA','provincia_id'=>22],
['name'=>'PALLASCA','provincia_id'=>22],
['name'=>'TAUCA','provincia_id'=>22],
['name'=>'CONCHUCOS','provincia_id'=>22],
['name'=>'HUANDOVAL','provincia_id'=>22],
['name'=>'LLAPO','provincia_id'=>22],
['name'=>'CABANA','provincia_id'=>22],
['name'=>'PAROBAMBA','provincia_id'=>23],
['name'=>'QUINUABAMBA','provincia_id'=>23],
['name'=>'POMABAMBA','provincia_id'=>23],
['name'=>'HUAYLLAN','provincia_id'=>23],
['name'=>'COTAPARACO','provincia_id'=>24],
['name'=>'LLACLLIN','provincia_id'=>24],
['name'=>'PAMPAS CHICO','provincia_id'=>24],
['name'=>'RECUAY','provincia_id'=>24],
['name'=>'CATAC','provincia_id'=>24],
['name'=>'HUAYLLAPAMPA','provincia_id'=>24],
['name'=>'MARCA','provincia_id'=>24],
['name'=>'PARARIN','provincia_id'=>24],
['name'=>'TAPACOCHA','provincia_id'=>24],
['name'=>'TICAPAMPA','provincia_id'=>24],
['name'=>'CACERES DEL PERU','provincia_id'=>25],
['name'=>'MACATE','provincia_id'=>25],
['name'=>'NEPEÑA','provincia_id'=>25],
['name'=>'SAMANCO','provincia_id'=>25],
['name'=>'NUEVO CHIMBOTE','provincia_id'=>25],
['name'=>'SANTA','provincia_id'=>25],
['name'=>'COISHCO','provincia_id'=>25],
['name'=>'MORO','provincia_id'=>25],
['name'=>'CHIMBOTE','provincia_id'=>25],
['name'=>'SIHUAS','provincia_id'=>26],
['name'=>'CASHAPAMPA','provincia_id'=>26],
['name'=>'CHINGALPO','provincia_id'=>26],
['name'=>'QUICHES','provincia_id'=>26],
['name'=>'ACOBAMBA','provincia_id'=>26],
['name'=>'HUAYLLABAMBA','provincia_id'=>26],
['name'=>'RAGASH','provincia_id'=>26],
['name'=>'SAN JUAN','provincia_id'=>26],
['name'=>'SICSIBAMBA','provincia_id'=>26],
['name'=>'ALFONSO UGARTE','provincia_id'=>26],
['name'=>'YUNGAY','provincia_id'=>27],
['name'=>'CASCAPARA','provincia_id'=>27],
['name'=>'MATACOTO','provincia_id'=>27],
['name'=>'QUILLO','provincia_id'=>27],
['name'=>'RANRAHIRCA','provincia_id'=>27],
['name'=>'SHUPLUY','provincia_id'=>27],
['name'=>'MANCOS','provincia_id'=>27],
['name'=>'YANAMA','provincia_id'=>27],
['name'=>'TAMBURCO','provincia_id'=>28],
['name'=>'LAMBRAMA','provincia_id'=>28],
['name'=>'CURAHUASI','provincia_id'=>28],
['name'=>'CHACOCHE','provincia_id'=>28],
['name'=>'PICHIRHUA','provincia_id'=>28],
['name'=>'SAN PEDRO DE CACHORA','provincia_id'=>28],
['name'=>'HUANIPACA','provincia_id'=>28],
['name'=>'ABANCAY','provincia_id'=>28],
['name'=>'CIRCA','provincia_id'=>28],
['name'=>'SANTA MARIA DE CHICMO','provincia_id'=>29],
['name'=>'KAQUIABAMBA','provincia_id'=>29],
['name'=>'CHIARA','provincia_id'=>29],
['name'=>'TURPO','provincia_id'=>29],
['name'=>'SAN ANTONIO DE CACHI','provincia_id'=>29],
['name'=>'SAN JERONIMO','provincia_id'=>29],
['name'=>'ANDAHUAYLAS','provincia_id'=>29],
['name'=>'PACOBAMBA','provincia_id'=>29],
['name'=>'PACUCHA','provincia_id'=>29],
['name'=>'HUAYANA','provincia_id'=>29],
['name'=>'PAMPACHIRI','provincia_id'=>29],
['name'=>'POMACOCHA','provincia_id'=>29],
['name'=>'KISHUARA','provincia_id'=>29],
['name'=>'TALAVERA','provincia_id'=>29],
['name'=>'ANDARAPA','provincia_id'=>29],
['name'=>'SAN MIGUEL DE CHACCRAMPA','provincia_id'=>29],
['name'=>'TUMAY HUARACA','provincia_id'=>29],
['name'=>'HUANCARAY','provincia_id'=>29],
['name'=>'HUANCARAMA','provincia_id'=>29],
['name'=>'JOSE MARIA ARGUEDAS','provincia_id'=>29],
['name'=>'SABAINO','provincia_id'=>30],
['name'=>'JUAN ESPINOZA MEDRANO','provincia_id'=>30],
['name'=>'ANTABAMBA','provincia_id'=>30],
['name'=>'HUAQUIRCA','provincia_id'=>30],
['name'=>'OROPESA','provincia_id'=>30],
['name'=>'PACHACONAS','provincia_id'=>30],
['name'=>'EL ORO','provincia_id'=>30],
['name'=>'LUCRE','provincia_id'=>31],
['name'=>'CHAPIMARCA','provincia_id'=>31],
['name'=>'COLCABAMBA','provincia_id'=>31],
['name'=>'COTARUSE','provincia_id'=>31],
['name'=>'SORAYA','provincia_id'=>31],
['name'=>'TAPAIRIHUA','provincia_id'=>31],
['name'=>'JUSTO APU SAHUARAURA','provincia_id'=>31],
['name'=>'CARAYBAMBA','provincia_id'=>31],
['name'=>'CHALHUANCA','provincia_id'=>31],
['name'=>'YANACA','provincia_id'=>31],
['name'=>'SAÑAYCA','provincia_id'=>31],
['name'=>'HUAYLLO','provincia_id'=>31],
['name'=>'TORAYA','provincia_id'=>31],
['name'=>'TINTAY','provincia_id'=>31],
['name'=>'POCOHUANCA','provincia_id'=>31],
['name'=>'CAPAYA','provincia_id'=>31],
['name'=>'SAN JUAN DE CHACÑA','provincia_id'=>31],
['name'=>'CHINCHEROS','provincia_id'=>33],
['name'=>'URANMARCA','provincia_id'=>33],
['name'=>'RANRACANCHA','provincia_id'=>33],
['name'=>'HUACCANA','provincia_id'=>33],
['name'=>'OCOBAMBA','provincia_id'=>33],
['name'=>'EL PORVENIR','provincia_id'=>33],
['name'=>'ROCCHACC','provincia_id'=>33],
['name'=>'LOS CHANKAS','provincia_id'=>33],
['name'=>'ANCO_HUALLO','provincia_id'=>33],
['name'=>'COCHARCAS','provincia_id'=>33],
['name'=>'ONGOY','provincia_id'=>33],
['name'=>'COTABAMBAS','provincia_id'=>32],
['name'=>'HAQUIRA','provincia_id'=>32],
['name'=>'CHALLHUAHUACHO','provincia_id'=>32],
['name'=>'MARA','provincia_id'=>32],
['name'=>'COYLLURQUI','provincia_id'=>32],
['name'=>'TAMBOBAMBA','provincia_id'=>32],
['name'=>'MAMARA','provincia_id'=>34],
['name'=>'PROGRESO','provincia_id'=>34],
['name'=>'VIRUNDO','provincia_id'=>34],
['name'=>'SAN ANTONIO','provincia_id'=>34],
['name'=>'PATAYPAMPA','provincia_id'=>34],
['name'=>'SANTA ROSA','provincia_id'=>34],
['name'=>'CHUQUIBAMBILLA','provincia_id'=>34],
['name'=>'VILCABAMBA','provincia_id'=>34],
['name'=>'MICAELA BASTIDAS','provincia_id'=>34],
['name'=>'TURPAY','provincia_id'=>34],
['name'=>'GAMARRA','provincia_id'=>34],
['name'=>'CURASCO','provincia_id'=>34],
['name'=>'CURPAHUASI','provincia_id'=>34],
['name'=>'HUAYLLATI','provincia_id'=>34],
['name'=>'QUEQUEÑA','provincia_id'=>35],
['name'=>'SAN JUAN DE TARUCANI','provincia_id'=>35],
['name'=>'SANTA ISABEL DE SIGUAS','provincia_id'=>35],
['name'=>'SOCABAYA','provincia_id'=>35],
['name'=>'PAUCARPATA','provincia_id'=>35],
['name'=>'CHIGUATA','provincia_id'=>35],
['name'=>'LA JOYA','provincia_id'=>35],
['name'=>'VITOR','provincia_id'=>35],
['name'=>'CAYMA','provincia_id'=>35],
['name'=>'POCSI','provincia_id'=>35],
['name'=>'AREQUIPA','provincia_id'=>35],
['name'=>'JOSE LUIS BUSTAMANTE Y RIVERO','provincia_id'=>35],
['name'=>'MIRAFLORES','provincia_id'=>35],
['name'=>'SACHACA','provincia_id'=>35],
['name'=>'MARIANO MELGAR','provincia_id'=>35],
['name'=>'CHARACATO','provincia_id'=>35],
['name'=>'POLOBAYA','provincia_id'=>35],
['name'=>'SANTA RITA DE SIGUAS','provincia_id'=>35],
['name'=>'TIABAYA','provincia_id'=>35],
['name'=>'UCHUMAYO','provincia_id'=>35],
['name'=>'YARABAMBA','provincia_id'=>35],
['name'=>'YURA','provincia_id'=>35],
['name'=>'CERRO COLORADO','provincia_id'=>35],
['name'=>'MOLLEBAYA','provincia_id'=>35],
['name'=>'SABANDIA','provincia_id'=>35],
['name'=>'SAN JUAN DE SIGUAS','provincia_id'=>35],
['name'=>'ALTO SELVA ALEGRE','provincia_id'=>35],
['name'=>'JACOBO HUNTER','provincia_id'=>35],
['name'=>'YANAHUARA','provincia_id'=>35],
['name'=>'JOSE MARIA QUIMPER','provincia_id'=>36],
['name'=>'MARIANO NICOLAS VALCARCEL','provincia_id'=>36],
['name'=>'MARISCAL CACERES','provincia_id'=>36],
['name'=>'OCOÑA','provincia_id'=>36],
['name'=>'CAMANA','provincia_id'=>36],
['name'=>'NICOLAS DE PIEROLA','provincia_id'=>36],
['name'=>'QUILCA','provincia_id'=>36],
['name'=>'SAMUEL PASTOR','provincia_id'=>36],
['name'=>'ACARI','provincia_id'=>37],
['name'=>'JAQUI','provincia_id'=>37],
['name'=>'QUICACHA','provincia_id'=>37],
['name'=>'BELLA UNION','provincia_id'=>37],
['name'=>'ATICO','provincia_id'=>37],
['name'=>'CAHUACHO','provincia_id'=>37],
['name'=>'CHAPARRA','provincia_id'=>37],
['name'=>'LOMAS','provincia_id'=>37],
['name'=>'YAUCA','provincia_id'=>37],
['name'=>'CARAVELI','provincia_id'=>37],
['name'=>'ATIQUIPA','provincia_id'=>37],
['name'=>'CHALA','provincia_id'=>37],
['name'=>'HUANUHUANU','provincia_id'=>37],
['name'=>'AYO','provincia_id'=>38],
['name'=>'CHACHAS','provincia_id'=>38],
['name'=>'CHILCAYMARCA','provincia_id'=>38],
['name'=>'MACHAGUAY','provincia_id'=>38],
['name'=>'ORCOPAMPA','provincia_id'=>38],
['name'=>'PAMPACOLCA','provincia_id'=>38],
['name'=>'URACA','provincia_id'=>38],
['name'=>'VIRACO','provincia_id'=>38],
['name'=>'TIPAN','provincia_id'=>38],
['name'=>'APLAO','provincia_id'=>38],
['name'=>'HUANCARQUI','provincia_id'=>38],
['name'=>'UÑON','provincia_id'=>38],
['name'=>'ANDAGUA','provincia_id'=>38],
['name'=>'CHOCO','provincia_id'=>38],
['name'=>'COPORAQUE','provincia_id'=>39],
['name'=>'HUAMBO','provincia_id'=>39],
['name'=>'LARI','provincia_id'=>39],
['name'=>'ACHOMA','provincia_id'=>39],
['name'=>'YANQUE','provincia_id'=>39],
['name'=>'LLUTA','provincia_id'=>39],
['name'=>'MACA','provincia_id'=>39],
['name'=>'MADRIGAL','provincia_id'=>39],
['name'=>'TAPAY','provincia_id'=>39],
['name'=>'CABANACONDE','provincia_id'=>39],
['name'=>'TUTI','provincia_id'=>39],
['name'=>'MAJES','provincia_id'=>39],
['name'=>'HUANCA','provincia_id'=>39],
['name'=>'ICHUPAMPA','provincia_id'=>39],
['name'=>'CALLALLI','provincia_id'=>39],
['name'=>'SAN ANTONIO DE CHUCA','provincia_id'=>39],
['name'=>'SIBAYO','provincia_id'=>39],
['name'=>'TISCO','provincia_id'=>39],
['name'=>'CHIVAY','provincia_id'=>39],
['name'=>'CAYLLOMA','provincia_id'=>39],
['name'=>'IRAY','provincia_id'=>40],
['name'=>'YANAQUIHUA','provincia_id'=>40],
['name'=>'CHUQUIBAMBA','provincia_id'=>40],
['name'=>'ANDARAY','provincia_id'=>40],
['name'=>'SALAMANCA','provincia_id'=>40],
['name'=>'CAYARANI','provincia_id'=>40],
['name'=>'CHICHAS','provincia_id'=>40],
['name'=>'RIO GRANDE','provincia_id'=>40],
['name'=>'ISLAY','provincia_id'=>41],
['name'=>'PUNTA DE BOMBON','provincia_id'=>41],
['name'=>'MOLLENDO','provincia_id'=>41],
['name'=>'COCACHACRA','provincia_id'=>41],
['name'=>'MEJIA','provincia_id'=>41],
['name'=>'DEAN VALDIVIA','provincia_id'=>41],
['name'=>'COTAHUASI','provincia_id'=>42],
['name'=>'TOMEPAMPA','provincia_id'=>42],
['name'=>'TAURIA','provincia_id'=>42],
['name'=>'QUECHUALLA','provincia_id'=>42],
['name'=>'TORO','provincia_id'=>42],
['name'=>'ALCA','provincia_id'=>42],
['name'=>'CHARCANA','provincia_id'=>42],
['name'=>'HUAYNACOTAS','provincia_id'=>42],
['name'=>'PAMPAMARCA','provincia_id'=>42],
['name'=>'PUYCA','provincia_id'=>42],
['name'=>'SAYLA','provincia_id'=>42],
['name'=>'TOTOS','provincia_id'=>44],
['name'=>'LOS MOROCHUCOS','provincia_id'=>44],
['name'=>'CHUSCHI','provincia_id'=>44],
['name'=>'CANGALLO','provincia_id'=>44],
['name'=>'MARIA PARADO DE BELLIDO','provincia_id'=>44],
['name'=>'PARAS','provincia_id'=>44],
['name'=>'ANDRES AVELINO CACERES DORREGARAY','provincia_id'=>43],
['name'=>'SOCOS','provincia_id'=>43],
['name'=>'OCROS','provincia_id'=>43],
['name'=>'CHIARA','provincia_id'=>43],
['name'=>'SAN JUAN BAUTISTA','provincia_id'=>43],
['name'=>'ACOS VINCHOS','provincia_id'=>43],
['name'=>'CARMEN ALTO','provincia_id'=>43],
['name'=>'ACOCRO','provincia_id'=>43],
['name'=>'TAMBILLO','provincia_id'=>43],
['name'=>'SANTIAGO DE PISCHA','provincia_id'=>43],
['name'=>'VINCHOS','provincia_id'=>43],
['name'=>'AYACUCHO','provincia_id'=>43],
['name'=>'JESUS NAZARENO','provincia_id'=>43],
['name'=>'SAN JOSE DE TICLLAS','provincia_id'=>43],
['name'=>'QUINUA','provincia_id'=>43],
['name'=>'PACAYCASA','provincia_id'=>43],
['name'=>'SACSAMARCA','provincia_id'=>45],
['name'=>'SANTIAGO DE LUCANAMARCA','provincia_id'=>45],
['name'=>'SANCOS','provincia_id'=>45],
['name'=>'CARAPO','provincia_id'=>45],
['name'=>'UCHURACCAY','provincia_id'=>46],
['name'=>'CHACA','provincia_id'=>46],
['name'=>'SANTILLANA','provincia_id'=>46],
['name'=>'CANAYRE','provincia_id'=>46],
['name'=>'PUCACOLPA','provincia_id'=>46],
['name'=>'HUAMANGUILLA','provincia_id'=>46],
['name'=>'IGUAIN','provincia_id'=>46],
['name'=>'HUANTA','provincia_id'=>46],
['name'=>'AYAHUANCO','provincia_id'=>46],
['name'=>'SIVIA','provincia_id'=>46],
['name'=>'LURICOCHA','provincia_id'=>46],
['name'=>'LLOCHEGUA','provincia_id'=>46],
['name'=>'SAN MIGUEL','provincia_id'=>47],
['name'=>'TAMBO','provincia_id'=>47],
['name'=>'AYNA','provincia_id'=>47],
['name'=>'ANCHIHUAY','provincia_id'=>47],
['name'=>'ORONCCOY','provincia_id'=>47],
['name'=>'CHILCAS','provincia_id'=>47],
['name'=>'ANCO','provincia_id'=>47],
['name'=>'LUIS CARRANZA','provincia_id'=>47],
['name'=>'CHUNGUI','provincia_id'=>47],
['name'=>'SANTA ROSA','provincia_id'=>47],
['name'=>'SAMUGARI','provincia_id'=>47],
['name'=>'LEONCIO PRADO','provincia_id'=>48],
['name'=>'CHAVIÑA','provincia_id'=>48],
['name'=>'SAN PEDRO','provincia_id'=>48],
['name'=>'PUQUIO','provincia_id'=>48],
['name'=>'OCAÑA','provincia_id'=>48],
['name'=>'CHIPAO','provincia_id'=>48],
['name'=>'SANTA ANA DE HUAYCAHUACHO','provincia_id'=>48],
['name'=>'AUCARA','provincia_id'=>48],
['name'=>'SAISA','provincia_id'=>48],
['name'=>'SAN CRISTOBAL','provincia_id'=>48],
['name'=>'SAN JUAN','provincia_id'=>48],
['name'=>'OTOCA','provincia_id'=>48],
['name'=>'LLAUTA','provincia_id'=>48],
['name'=>'SANCOS','provincia_id'=>48],
['name'=>'SANTA LUCIA','provincia_id'=>48],
['name'=>'LUCANAS','provincia_id'=>48],
['name'=>'CARMEN SALCEDO','provincia_id'=>48],
['name'=>'CABANA','provincia_id'=>48],
['name'=>'LARAMATE','provincia_id'=>48],
['name'=>'SAN PEDRO DE PALCO','provincia_id'=>48],
['name'=>'HUAC-HUAS','provincia_id'=>48],
['name'=>'PUYUSCA','provincia_id'=>49],
['name'=>'CHUMPI','provincia_id'=>49],
['name'=>'SAN FRANCISCO DE RAVACAYCO','provincia_id'=>49],
['name'=>'PACAPAUSA','provincia_id'=>49],
['name'=>'PULLO','provincia_id'=>49],
['name'=>'CORACORA','provincia_id'=>49],
['name'=>'UPAHUACHO','provincia_id'=>49],
['name'=>'CORONEL CASTAÑEDA','provincia_id'=>49],
['name'=>'CORCULLA','provincia_id'=>50],
['name'=>'PAUSA','provincia_id'=>50],
['name'=>'OYOLO','provincia_id'=>50],
['name'=>'COLTA','provincia_id'=>50],
['name'=>'SARA SARA','provincia_id'=>50],
['name'=>'SAN JOSE DE USHUA','provincia_id'=>50],
['name'=>'PARARCA','provincia_id'=>50],
['name'=>'SAN JAVIER DE ALPABAMBA','provincia_id'=>50],
['name'=>'MARCABAMBA','provincia_id'=>50],
['name'=>'LAMPA','provincia_id'=>50],
['name'=>'SORAS','provincia_id'=>51],
['name'=>'SAN SALVADOR DE QUIJE','provincia_id'=>51],
['name'=>'SAN PEDRO DE LARCAY','provincia_id'=>51],
['name'=>'HUACAÑA','provincia_id'=>51],
['name'=>'MORCOLLA','provincia_id'=>51],
['name'=>'QUEROBAMBA','provincia_id'=>51],
['name'=>'PAICO','provincia_id'=>51],
['name'=>'CHILCAYOC','provincia_id'=>51],
['name'=>'SANTIAGO DE PAUCARAY','provincia_id'=>51],
['name'=>'CHALCOS','provincia_id'=>51],
['name'=>'BELEN','provincia_id'=>51],
['name'=>'ASQUIPATA','provincia_id'=>52],
['name'=>'APONGO','provincia_id'=>52],
['name'=>'HUAYA','provincia_id'=>52],
['name'=>'HUANCARAYLLA','provincia_id'=>52],
['name'=>'COLCA','provincia_id'=>52],
['name'=>'CANARIA','provincia_id'=>52],
['name'=>'CAYARA','provincia_id'=>52],
['name'=>'SARHUA','provincia_id'=>52],
['name'=>'HUAMANQUIQUIA','provincia_id'=>52],
['name'=>'HUANCAPI','provincia_id'=>52],
['name'=>'ALCAMENCA','provincia_id'=>52],
['name'=>'VILCANCHOS','provincia_id'=>52],
['name'=>'INDEPENDENCIA','provincia_id'=>53],
['name'=>'VISCHONGO','provincia_id'=>53],
['name'=>'ACCOMARCA','provincia_id'=>53],
['name'=>'HUAMBALPA','provincia_id'=>53],
['name'=>'CARHUANCA','provincia_id'=>53],
['name'=>'SAURAMA','provincia_id'=>53],
['name'=>'VILCAS HUAMAN','provincia_id'=>53],
['name'=>'CONCEPCION','provincia_id'=>53],
['name'=>'CAJABAMBA','provincia_id'=>55],
['name'=>'CACHACHI','provincia_id'=>55],
['name'=>'CONDEBAMBA','provincia_id'=>55],
['name'=>'SITACOCHA','provincia_id'=>55],
['name'=>'LLACANORA','provincia_id'=>54],
['name'=>'LOS BAÑOS DEL INCA','provincia_id'=>54],
['name'=>'MAGDALENA','provincia_id'=>54],
['name'=>'NAMORA','provincia_id'=>54],
['name'=>'SAN JUAN','provincia_id'=>54],
['name'=>'ASUNCION','provincia_id'=>54],
['name'=>'CHETILLA','provincia_id'=>54],
['name'=>'COSPAN','provincia_id'=>54],
['name'=>'JESUS','provincia_id'=>54],
['name'=>'CAJAMARCA','provincia_id'=>54],
['name'=>'MATARA','provincia_id'=>54],
['name'=>'ENCAÑADA','provincia_id'=>54],
['name'=>'CELENDIN','provincia_id'=>56],
['name'=>'UTCO','provincia_id'=>56],
['name'=>'CHUMUCH','provincia_id'=>56],
['name'=>'JORGE CHAVEZ','provincia_id'=>56],
['name'=>'JOSE GALVEZ','provincia_id'=>56],
['name'=>'CORTEGANA','provincia_id'=>56],
['name'=>'HUASMIN','provincia_id'=>56],
['name'=>'MIGUEL IGLESIAS','provincia_id'=>56],
['name'=>'LA LIBERTAD DE PALLAN','provincia_id'=>56],
['name'=>'SUCRE','provincia_id'=>56],
['name'=>'OXAMARCA','provincia_id'=>56],
['name'=>'SOROCHUCO','provincia_id'=>56],
['name'=>'CHIMBAN','provincia_id'=>57],
['name'=>'LAJAS','provincia_id'=>57],
['name'=>'PION','provincia_id'=>57],
['name'=>'CHOTA','provincia_id'=>57],
['name'=>'CHADIN','provincia_id'=>57],
['name'=>'CONCHAN','provincia_id'=>57],
['name'=>'ANGUIA','provincia_id'=>57],
['name'=>'COCHABAMBA','provincia_id'=>57],
['name'=>'CHOROPAMPA','provincia_id'=>57],
['name'=>'LLAMA','provincia_id'=>57],
['name'=>'MIRACOSTA','provincia_id'=>57],
['name'=>'PACCHA','provincia_id'=>57],
['name'=>'QUEROCOTO','provincia_id'=>57],
['name'=>'SAN JUAN DE LICUPIS','provincia_id'=>57],
['name'=>'CHIGUIRIP','provincia_id'=>57],
['name'=>'TOCMOCHE','provincia_id'=>57],
['name'=>'HUAMBOS','provincia_id'=>57],
['name'=>'TACABAMBA','provincia_id'=>57],
['name'=>'CHALAMARCA','provincia_id'=>57],
['name'=>'CUPISNIQUE','provincia_id'=>58],
['name'=>'GUZMANGO','provincia_id'=>58],
['name'=>'CHILETE','provincia_id'=>58],
['name'=>'SANTA CRUZ DE TOLED','provincia_id'=>58],
['name'=>'TANTARICA','provincia_id'=>58],
['name'=>'SAN BENITO','provincia_id'=>58],
['name'=>'CONTUMAZA','provincia_id'=>58],
['name'=>'YONAN','provincia_id'=>58],
['name'=>'SAN JUAN DE CUTERVO','provincia_id'=>59],
['name'=>'SAN LUIS DE LUCMA','provincia_id'=>59],
['name'=>'SOCOTA','provincia_id'=>59],
['name'=>'CUTERVO','provincia_id'=>59],
['name'=>'QUEROCOTILLO','provincia_id'=>59],
['name'=>'CUJILLO','provincia_id'=>59],
['name'=>'LA RAMADA','provincia_id'=>59],
['name'=>'SANTO TOMAS','provincia_id'=>59],
['name'=>'CHOROS','provincia_id'=>59],
['name'=>'SANTA CRUZ','provincia_id'=>59],
['name'=>'CALLAYUC','provincia_id'=>59],
['name'=>'SAN ANDRES DE CUTERVO','provincia_id'=>59],
['name'=>'SANTO DOMINGO DE LA CAPILLA','provincia_id'=>59],
['name'=>'TORIBIO CASANOVA','provincia_id'=>59],
['name'=>'PIMPINGOS','provincia_id'=>59],
['name'=>'BAMBAMARCA','provincia_id'=>60],
['name'=>'CHUGUR','provincia_id'=>60],
['name'=>'HUALGAYOC','provincia_id'=>60],
['name'=>'SAN JOSE DEL ALTO','provincia_id'=>61],
['name'=>'CHONTALI','provincia_id'=>61],
['name'=>'PUCARA','provincia_id'=>61],
['name'=>'SANTA ROSA','provincia_id'=>61],
['name'=>'SALLIQUE','provincia_id'=>61],
['name'=>'POMAHUACA','provincia_id'=>61],
['name'=>'COLASAY','provincia_id'=>61],
['name'=>'SAN FELIPE','provincia_id'=>61],
['name'=>'BELLAVISTA','provincia_id'=>61],
['name'=>'JAEN','provincia_id'=>61],
['name'=>'HUABAL','provincia_id'=>61],
['name'=>'LAS PIRIAS','provincia_id'=>61],
['name'=>'SAN IGNACIO','provincia_id'=>62],
['name'=>'HUARANGO','provincia_id'=>62],
['name'=>'SAN JOSE DE LOURDES','provincia_id'=>62],
['name'=>'CHIRINOS','provincia_id'=>62],
['name'=>'LA COIPA','provincia_id'=>62],
['name'=>'NAMBALLE','provincia_id'=>62],
['name'=>'TABACONAS','provincia_id'=>62],
['name'=>'CHANCAY','provincia_id'=>63],
['name'=>'GREGORIO PITA','provincia_id'=>63],
['name'=>'JOSE MANUEL QUIROZ','provincia_id'=>63],
['name'=>'JOSE SABOGAL','provincia_id'=>63],
['name'=>'PEDRO GALVEZ','provincia_id'=>63],
['name'=>'EDUARDO VILLANUEVA','provincia_id'=>63],
['name'=>'ICHOCAN','provincia_id'=>63],
['name'=>'SAN GREGORIO','provincia_id'=>64],
['name'=>'SAN MIGUEL','provincia_id'=>64],
['name'=>'CALQUIS','provincia_id'=>64],
['name'=>'SAN SILVESTRE DE COCHAN','provincia_id'=>64],
['name'=>'CATILLUC','provincia_id'=>64],
['name'=>'BOLIVAR','provincia_id'=>64],
['name'=>'LLAPA','provincia_id'=>64],
['name'=>'NANCHOC','provincia_id'=>64],
['name'=>'EL PRADO','provincia_id'=>64],
['name'=>'NIEPOS','provincia_id'=>64],
['name'=>'TONGOD','provincia_id'=>64],
['name'=>'LA FLORIDA','provincia_id'=>64],
['name'=>'UNION AGUA BLANCA','provincia_id'=>64],
['name'=>'SAN BERNARDINO','provincia_id'=>65],
['name'=>'SAN LUIS','provincia_id'=>65],
['name'=>'SAN PABLO','provincia_id'=>65],
['name'=>'TUMBADEN','provincia_id'=>65],
['name'=>'SANTA CRUZ','provincia_id'=>66],
['name'=>'NINABAMBA','provincia_id'=>66],
['name'=>'YAUYUCAN','provincia_id'=>66],
['name'=>'ANDABAMBA','provincia_id'=>66],
['name'=>'LA ESPERANZA','provincia_id'=>66],
['name'=>'SEXI','provincia_id'=>66],
['name'=>'CATACHE','provincia_id'=>66],
['name'=>'CHANCAYBAÑOS','provincia_id'=>66],
['name'=>'PULAN','provincia_id'=>66],
['name'=>'SAUCEPAMPA','provincia_id'=>66],
['name'=>'UTICYACU','provincia_id'=>66],
['name'=>'POMACANCHI','provincia_id'=>68],
['name'=>'ACOPIA','provincia_id'=>68],
['name'=>'MOSOC LLACTA','provincia_id'=>68],
['name'=>'ACOMAYO','provincia_id'=>68],
['name'=>'RONDOCAN','provincia_id'=>68],
['name'=>'SANGARARA','provincia_id'=>68],
['name'=>'ACOS','provincia_id'=>68],
['name'=>'MOLLEPATA','provincia_id'=>69],
['name'=>'HUAROCONDO','provincia_id'=>69],
['name'=>'ANTA','provincia_id'=>69],
['name'=>'ANCAHUASI','provincia_id'=>69],
['name'=>'CACHIMAYO','provincia_id'=>69],
['name'=>'ZURITE','provincia_id'=>69],
['name'=>'LIMATAMBO','provincia_id'=>69],
['name'=>'PUCYURA','provincia_id'=>69],
['name'=>'CHINCHAYPUJIO','provincia_id'=>69],
['name'=>'LARES','provincia_id'=>70],
['name'=>'PISAC','provincia_id'=>70],
['name'=>'TARAY','provincia_id'=>70],
['name'=>'LAMAY','provincia_id'=>70],
['name'=>'SAN SALVADOR','provincia_id'=>70],
['name'=>'CALCA','provincia_id'=>70],
['name'=>'YANATILE','provincia_id'=>70],
['name'=>'COYA','provincia_id'=>70],
['name'=>'LAYO','provincia_id'=>71],
['name'=>'CHECCA','provincia_id'=>71],
['name'=>'QUEHUE','provincia_id'=>71],
['name'=>'KUNTURKANKI','provincia_id'=>71],
['name'=>'LANGUI','provincia_id'=>71],
['name'=>'TUPAC AMARU','provincia_id'=>71],
['name'=>'YANAOCA','provincia_id'=>71],
['name'=>'PAMPAMARCA','provincia_id'=>71],
['name'=>'CHECACUPE','provincia_id'=>72],
['name'=>'SICUANI','provincia_id'=>72],
['name'=>'COMBAPATA','provincia_id'=>72],
['name'=>'MARANGANI','provincia_id'=>72],
['name'=>'PITUMARCA','provincia_id'=>72],
['name'=>'SAN PEDRO','provincia_id'=>72],
['name'=>'SAN PABLO','provincia_id'=>72],
['name'=>'TINTA','provincia_id'=>72],
['name'=>'CAPACMARCA','provincia_id'=>73],
['name'=>'CHAMACA','provincia_id'=>73],
['name'=>'COLQUEMARCA','provincia_id'=>73],
['name'=>'LLUSCO','provincia_id'=>73],
['name'=>'QUIÑOTA','provincia_id'=>73],
['name'=>'SANTO TOMAS','provincia_id'=>73],
['name'=>'LIVITACA','provincia_id'=>73],
['name'=>'VELILLE','provincia_id'=>73],
['name'=>'WANCHAQ','provincia_id'=>67],
['name'=>'SANTIAGO','provincia_id'=>67],
['name'=>'SAN SEBASTIAN','provincia_id'=>67],
['name'=>'SAN JERONIMO','provincia_id'=>67],
['name'=>'CCORCA','provincia_id'=>67],
['name'=>'POROY','provincia_id'=>67],
['name'=>'SAYLLA','provincia_id'=>67],
['name'=>'CUSCO','provincia_id'=>67],
['name'=>'PALLPATA','provincia_id'=>74],
['name'=>'PICHIGUA','provincia_id'=>74],
['name'=>'SUYCKUTAMBO','provincia_id'=>74],
['name'=>'OCORURO','provincia_id'=>74],
['name'=>'ALTO PICHIGUA','provincia_id'=>74],
['name'=>'CONDOROMA','provincia_id'=>74],
['name'=>'ESPINAR','provincia_id'=>74],
['name'=>'COPORAQUE','provincia_id'=>74],
['name'=>'INKAWASI','provincia_id'=>75],
['name'=>'VILLA VIRGEN','provincia_id'=>75],
['name'=>'ECHARATE','provincia_id'=>75],
['name'=>'MARANURA','provincia_id'=>75],
['name'=>'SANTA TERESA','provincia_id'=>75],
['name'=>'PICHARI','provincia_id'=>75],
['name'=>'SANTA ANA','provincia_id'=>75],
['name'=>'MEGANTONI','provincia_id'=>75],
['name'=>'HUAYOPATA','provincia_id'=>75],
['name'=>'OCOBAMBA','provincia_id'=>75],
['name'=>'VILCABAMBA','provincia_id'=>75],
['name'=>'VILLA KINTIARINA','provincia_id'=>75],
['name'=>'QUELLOUNO','provincia_id'=>75],
['name'=>'KIMBIRI','provincia_id'=>75],
['name'=>'PACCARITAMBO','provincia_id'=>76],
['name'=>'COLCHA','provincia_id'=>76],
['name'=>'PILLPINTO','provincia_id'=>76],
['name'=>'YAURISQUE','provincia_id'=>76],
['name'=>'ACCHA','provincia_id'=>76],
['name'=>'CCAPI','provincia_id'=>76],
['name'=>'HUANOQUITE','provincia_id'=>76],
['name'=>'OMACHA','provincia_id'=>76],
['name'=>'PARURO','provincia_id'=>76],
['name'=>'CHALLABAMBA','provincia_id'=>77],
['name'=>'KOSÑIPATA','provincia_id'=>77],
['name'=>'COLQUEPATA','provincia_id'=>77],
['name'=>'CAICAY','provincia_id'=>77],
['name'=>'HUANCARANI','provincia_id'=>77],
['name'=>'PAUCARTAMBO','provincia_id'=>77],
['name'=>'LUCRE','provincia_id'=>78],
['name'=>'QUIQUIJANA','provincia_id'=>78],
['name'=>'CCARHUAYO','provincia_id'=>78],
['name'=>'CAMANTI','provincia_id'=>78],
['name'=>'CUSIPATA','provincia_id'=>78],
['name'=>'OCONGATE','provincia_id'=>78],
['name'=>'OROPESA','provincia_id'=>78],
['name'=>'URCOS','provincia_id'=>78],
['name'=>'ANDAHUAYLILLAS','provincia_id'=>78],
['name'=>'HUARO','provincia_id'=>78],
['name'=>'MARCAPATA','provincia_id'=>78],
['name'=>'CCATCA','provincia_id'=>78],
['name'=>'CHINCHERO','provincia_id'=>79],
['name'=>'OLLANTAYTAMBO','provincia_id'=>79],
['name'=>'YUCAY','provincia_id'=>79],
['name'=>'MARAS','provincia_id'=>79],
['name'=>'MACHUPICCHU','provincia_id'=>79],
['name'=>'URUBAMBA','provincia_id'=>79],
['name'=>'HUAYLLABAMBA','provincia_id'=>79],
['name'=>'ACOBAMBA','provincia_id'=>81],
['name'=>'MARCAS','provincia_id'=>81],
['name'=>'CAJA','provincia_id'=>81],
['name'=>'ANTA','provincia_id'=>81],
['name'=>'POMACOCHA','provincia_id'=>81],
['name'=>'PAUCARA','provincia_id'=>81],
['name'=>'ROSARIO','provincia_id'=>81],
['name'=>'ANDABAMBA','provincia_id'=>81],
['name'=>'SANTO TOMAS DE PATA','provincia_id'=>82],
['name'=>'SECCLLA','provincia_id'=>82],
['name'=>'CONGALLA','provincia_id'=>82],
['name'=>'LIRCAY','provincia_id'=>82],
['name'=>'CCOCHACCASA','provincia_id'=>82],
['name'=>'ANCHONGA','provincia_id'=>82],
['name'=>'HUANCA-HUANCA','provincia_id'=>82],
['name'=>'CHINCHO','provincia_id'=>82],
['name'=>'SAN ANTONIO DE ANTAPARCO','provincia_id'=>82],
['name'=>'JULCAMARCA','provincia_id'=>82],
['name'=>'HUAYLLAY GRANDE','provincia_id'=>82],
['name'=>'CALLANMARCA','provincia_id'=>82],
['name'=>'CAPILLAS','provincia_id'=>83],
['name'=>'CHUPAMARCA','provincia_id'=>83],
['name'=>'COCAS','provincia_id'=>83],
['name'=>'TICRAPO','provincia_id'=>83],
['name'=>'MOLLEPAMPA','provincia_id'=>83],
['name'=>'ARMA','provincia_id'=>83],
['name'=>'TANTARA','provincia_id'=>83],
['name'=>'AURAHUA','provincia_id'=>83],
['name'=>'SANTA ANA','provincia_id'=>83],
['name'=>'SAN JUAN','provincia_id'=>83],
['name'=>'CASTROVIRREYNA','provincia_id'=>83],
['name'=>'HUACHOS','provincia_id'=>83],
['name'=>'HUAMATAMBO','provincia_id'=>83],
['name'=>'COSME','provincia_id'=>84],
['name'=>'LA MERCED','provincia_id'=>84],
['name'=>'PACHAMARCA','provincia_id'=>84],
['name'=>'CHINCHIHUASI','provincia_id'=>84],
['name'=>'CHURCAMPA','provincia_id'=>84],
['name'=>'ANCO','provincia_id'=>84],
['name'=>'EL CARMEN','provincia_id'=>84],
['name'=>'PAUCARBAMBA','provincia_id'=>84],
['name'=>'SAN MIGUEL DE MAYOCC','provincia_id'=>84],
['name'=>'SAN PEDRO DE CORIS','provincia_id'=>84],
['name'=>'LOCROJA','provincia_id'=>84],
['name'=>'HUACHOCOLPA','provincia_id'=>80],
['name'=>'ACORIA','provincia_id'=>80],
['name'=>'MANTA','provincia_id'=>80],
['name'=>'CONAYCA','provincia_id'=>80],
['name'=>'VILCA','provincia_id'=>80],
['name'=>'CUENCA','provincia_id'=>80],
['name'=>'MARISCAL CACERES','provincia_id'=>80],
['name'=>'HUANCAVELICA','provincia_id'=>80],
['name'=>'YAULI','provincia_id'=>80],
['name'=>'ASCENSION','provincia_id'=>80],
['name'=>'PALCA','provincia_id'=>80],
['name'=>'ACOBAMBILLA','provincia_id'=>80],
['name'=>'HUANDO','provincia_id'=>80],
['name'=>'NUEVO OCCORO','provincia_id'=>80],
['name'=>'LARIA','provincia_id'=>80],
['name'=>'IZCUCHACA','provincia_id'=>80],
['name'=>'MOYA','provincia_id'=>80],
['name'=>'HUAYLLAHUARA','provincia_id'=>80],
['name'=>'PILCHACA','provincia_id'=>80],
['name'=>'SANTO DOMINGO DE CAPILLAS','provincia_id'=>85],
['name'=>'SAN ANTONIO DE CUSICANCHA','provincia_id'=>85],
['name'=>'SANTIAGO DE CHOCORVOS','provincia_id'=>85],
['name'=>'SAN ISIDRO','provincia_id'=>85],
['name'=>'OCOYO','provincia_id'=>85],
['name'=>'QUERCO','provincia_id'=>85],
['name'=>'AYAVI','provincia_id'=>85],
['name'=>'HUAYTARA','provincia_id'=>85],
['name'=>'QUITO-ARMA','provincia_id'=>85],
['name'=>'PILPICHACA','provincia_id'=>85],
['name'=>'SAN FRANCISCO DE SANGAYAICO','provincia_id'=>85],
['name'=>'SANTIAGO DE QUIRAHUARA','provincia_id'=>85],
['name'=>'CORDOVA','provincia_id'=>85],
['name'=>'LARAMARCA','provincia_id'=>85],
['name'=>'HUAYACUNDO ARMA','provincia_id'=>85],
['name'=>'TAMBO','provincia_id'=>85],
['name'=>'ACRAQUIA','provincia_id'=>86],
['name'=>'DANIEL HERNANDEZ','provincia_id'=>86],
['name'=>'HUARIBAMBA','provincia_id'=>86],
['name'=>'SAN MARCOS DE ROCCHAC','provincia_id'=>86],
['name'=>'COLCABAMBA','provincia_id'=>86],
['name'=>'SURCUBAMBA','provincia_id'=>86],
['name'=>'ANDAYMARCA','provincia_id'=>86],
['name'=>'ÑAHUIMPUQUIO','provincia_id'=>86],
['name'=>'QUISHUAR','provincia_id'=>86],
['name'=>'SALCABAMBA','provincia_id'=>86],
['name'=>'SALCAHUASI','provincia_id'=>86],
['name'=>'QUICHUAS','provincia_id'=>86],
['name'=>'TINTAY PUNCU','provincia_id'=>86],
['name'=>'HUACHOCOLPA','provincia_id'=>86],
['name'=>'ACOSTAMBO','provincia_id'=>86],
['name'=>'ROBLE','provincia_id'=>86],
['name'=>'PICHOS','provincia_id'=>86],
['name'=>'SANTIAGO DE TUCUMA','provincia_id'=>86],
['name'=>'PAMPAS','provincia_id'=>86],
['name'=>'AHUAYCHA','provincia_id'=>86],
['name'=>'PAZOS','provincia_id'=>86],
['name'=>'AMBO','provincia_id'=>88],
['name'=>'CAYNA','provincia_id'=>88],
['name'=>'CONCHAMARCA','provincia_id'=>88],
['name'=>'SAN FRANCISCO','provincia_id'=>88],
['name'=>'TOMAY KICHWA','provincia_id'=>88],
['name'=>'SAN RAFAEL','provincia_id'=>88],
['name'=>'COLPAS','provincia_id'=>88],
['name'=>'HUACAR','provincia_id'=>88],
['name'=>'MARIAS','provincia_id'=>89],
['name'=>'CHUQUIS','provincia_id'=>89],
['name'=>'SILLAPATA','provincia_id'=>89],
['name'=>'PACHAS','provincia_id'=>89],
['name'=>'YANAS','provincia_id'=>89],
['name'=>'LA UNION','provincia_id'=>89],
['name'=>'RIPAN','provincia_id'=>89],
['name'=>'SHUNQUI','provincia_id'=>89],
['name'=>'QUIVILLA','provincia_id'=>89],
['name'=>'HUACAYBAMBA','provincia_id'=>90],
['name'=>'CANCHABAMBA','provincia_id'=>90],
['name'=>'COCHABAMBA','provincia_id'=>90],
['name'=>'PINRA','provincia_id'=>90],
['name'=>'SINGA','provincia_id'=>91],
['name'=>'JACAS GRANDE','provincia_id'=>91],
['name'=>'ARANCAY','provincia_id'=>91],
['name'=>'MONZON','provincia_id'=>91],
['name'=>'PUNCHAO','provincia_id'=>91],
['name'=>'PUÑOS','provincia_id'=>91],
['name'=>'TANTAMAYO','provincia_id'=>91],
['name'=>'JIRCAN','provincia_id'=>91],
['name'=>'MIRAFLORES','provincia_id'=>91],
['name'=>'LLATA','provincia_id'=>91],
['name'=>'CHAVIN DE PARIARCA','provincia_id'=>91],
['name'=>'HUANUCO','provincia_id'=>87],
['name'=>'CHURUBAMBA','provincia_id'=>87],
['name'=>'SAN PEDRO DE CHAULAN','provincia_id'=>87],
['name'=>'YACUS','provincia_id'=>87],
['name'=>'SANTA MARIA DEL VALLE','provincia_id'=>87],
['name'=>'SAN PABLO DE PILLAO','provincia_id'=>87],
['name'=>'AMARILIS','provincia_id'=>87],
['name'=>'YARUMAYO','provincia_id'=>87],
['name'=>'QUISQUI (KICHKI)','provincia_id'=>87],
['name'=>'MARGOS','provincia_id'=>87],
['name'=>'SAN FRANCISCO DE CAYRAN','provincia_id'=>87],
['name'=>'PILLCO MARCA','provincia_id'=>87],
['name'=>'CHINCHAO','provincia_id'=>87],
['name'=>'QUEROPALCA','provincia_id'=>96],
['name'=>'SAN FRANCISCO DE ASIS','provincia_id'=>96],
['name'=>'BAÑOS','provincia_id'=>96],
['name'=>'RONDOS','provincia_id'=>96],
['name'=>'SAN MIGUEL DE CAURI','provincia_id'=>96],
['name'=>'JESUS','provincia_id'=>96],
['name'=>'JIVIA','provincia_id'=>96],
['name'=>'CASTILLO GRANDE','provincia_id'=>92],
['name'=>'PUEBLO NUEVO','provincia_id'=>92],
['name'=>'RUPA-RUPA','provincia_id'=>92],
['name'=>'DANIEL ALOMIA ROBLES','provincia_id'=>92],
['name'=>'PUCAYACU','provincia_id'=>92],
['name'=>'SANTO DOMINGO DE ANDA','provincia_id'=>92],
['name'=>'HERMILIO VALDIZAN','provincia_id'=>92],
['name'=>'LUYANDO','provincia_id'=>92],
['name'=>'MARIANO DAMASO BERAUN','provincia_id'=>92],
['name'=>'JOSE CRESPO Y CASTILLO','provincia_id'=>92],
['name'=>'SANTA ROSA DE ALTO YANAJANCA','provincia_id'=>93],
['name'=>'HUACRACHUCO','provincia_id'=>93],
['name'=>'SAN BUENAVENTURA','provincia_id'=>93],
['name'=>'CHOLON','provincia_id'=>93],
['name'=>'LA MORADA','provincia_id'=>93],
['name'=>'PANAO','provincia_id'=>94],
['name'=>'CHAGLLA','provincia_id'=>94],
['name'=>'UMARI','provincia_id'=>94],
['name'=>'MOLINO','provincia_id'=>94],
['name'=>'TOURNAVISTA','provincia_id'=>95],
['name'=>'HONORIA','provincia_id'=>95],
['name'=>'YUYAPICHIS','provincia_id'=>95],
['name'=>'CODO DEL POZUZO','provincia_id'=>95],
['name'=>'PUERTO INCA','provincia_id'=>95],
['name'=>'CHACABAMBA','provincia_id'=>97],
['name'=>'PAMPAMARCA','provincia_id'=>97],
['name'=>'CHAVINILLO','provincia_id'=>97],
['name'=>'CAHUAC','provincia_id'=>97],
['name'=>'APARICIO POMARES','provincia_id'=>97],
['name'=>'JACAS CHICO','provincia_id'=>97],
['name'=>'CHORAS','provincia_id'=>97],
['name'=>'OBAS','provincia_id'=>97],
['name'=>'CHINCHA ALTA','provincia_id'=>99],
['name'=>'ALTO LARAN','provincia_id'=>99],
['name'=>'CHAVIN','provincia_id'=>99],
['name'=>'CHINCHA BAJA','provincia_id'=>99],
['name'=>'EL CARMEN','provincia_id'=>99],
['name'=>'SUNAMPE','provincia_id'=>99],
['name'=>'PUEBLO NUEVO','provincia_id'=>99],
['name'=>'GROCIO PRADO','provincia_id'=>99],
['name'=>'SAN JUAN DE YANAC','provincia_id'=>99],
['name'=>'SAN PEDRO DE HUACARPANA','provincia_id'=>99],
['name'=>'TAMBO DE MORA','provincia_id'=>99],
['name'=>'LOS AQUIJES','provincia_id'=>98],
['name'=>'OCUCAJE','provincia_id'=>98],
['name'=>'SAN JUAN BAUTISTA','provincia_id'=>98],
['name'=>'PACHACUTEC','provincia_id'=>98],
['name'=>'SALAS','provincia_id'=>98],
['name'=>'SAN JOSE DE LOS MOLINOS','provincia_id'=>98],
['name'=>'LA TINGUIÑA','provincia_id'=>98],
['name'=>'PARCONA','provincia_id'=>98],
['name'=>'SANTIAGO','provincia_id'=>98],
['name'=>'SUBTANJALLA','provincia_id'=>98],
['name'=>'TATE','provincia_id'=>98],
['name'=>'YAUCA DEL ROSARIO','provincia_id'=>98],
['name'=>'ICA','provincia_id'=>98],
['name'=>'PUEBLO NUEVO','provincia_id'=>98],
['name'=>'CHANGUILLO','provincia_id'=>100],
['name'=>'EL INGENIO','provincia_id'=>100],
['name'=>'VISTA ALEGRE','provincia_id'=>100],
['name'=>'NASCA','provincia_id'=>100],
['name'=>'MARCONA','provincia_id'=>100],
['name'=>'PALPA','provincia_id'=>101],
['name'=>'LLIPATA','provincia_id'=>101],
['name'=>'RIO GRANDE','provincia_id'=>101],
['name'=>'SANTA CRUZ','provincia_id'=>101],
['name'=>'TIBILLO','provincia_id'=>101],
['name'=>'SAN ANDRES','provincia_id'=>102],
['name'=>'SAN CLEMENTE','provincia_id'=>102],
['name'=>'TUPAC AMARU INCA','provincia_id'=>102],
['name'=>'PISCO','provincia_id'=>102],
['name'=>'HUANCANO','provincia_id'=>102],
['name'=>'HUMAY','provincia_id'=>102],
['name'=>'INDEPENDENCIA','provincia_id'=>102],
['name'=>'PARACAS','provincia_id'=>102],
['name'=>'PERENE','provincia_id'=>105],
['name'=>'PICHANAQUI','provincia_id'=>105],
['name'=>'SAN LUIS DE SHUARO','provincia_id'=>105],
['name'=>'CHANCHAMAYO','provincia_id'=>105],
['name'=>'VITOC','provincia_id'=>105],
['name'=>'SAN RAMON','provincia_id'=>105],
['name'=>'CHONGOS BAJO','provincia_id'=>111],
['name'=>'AHUAC','provincia_id'=>111],
['name'=>'SAN JUAN DE JARPA','provincia_id'=>111],
['name'=>'CHUPACA','provincia_id'=>111],
['name'=>'HUACHAC','provincia_id'=>111],
['name'=>'TRES DE DICIEMBRE','provincia_id'=>111],
['name'=>'YANACANCHA','provincia_id'=>111],
['name'=>'SAN JUAN DE ISCOS','provincia_id'=>111],
['name'=>'HUAMANCACA CHICO','provincia_id'=>111],
['name'=>'MATAHUASI','provincia_id'=>104],
['name'=>'SANTA ROSA DE OCOPA','provincia_id'=>104],
['name'=>'CHAMBARA','provincia_id'=>104],
['name'=>'MANZANARES','provincia_id'=>104],
['name'=>'ORCOTUNA','provincia_id'=>104],
['name'=>'ANDAMARCA','provincia_id'=>104],
['name'=>'CONCEPCION','provincia_id'=>104],
['name'=>'NUEVE DE JULIO','provincia_id'=>104],
['name'=>'ACO','provincia_id'=>104],
['name'=>'COMAS','provincia_id'=>104],
['name'=>'HEROINAS TOLEDO','provincia_id'=>104],
['name'=>'COCHAS','provincia_id'=>104],
['name'=>'MARISCAL CASTILLA','provincia_id'=>104],
['name'=>'MITO','provincia_id'=>104],
['name'=>'SAN JOSE DE QUERO','provincia_id'=>104],
['name'=>'EL TAMBO','provincia_id'=>103],
['name'=>'SAPALLANGA','provincia_id'=>103],
['name'=>'PARIAHUANCA','provincia_id'=>103],
['name'=>'SAN AGUSTIN','provincia_id'=>103],
['name'=>'SAÑO','provincia_id'=>103],
['name'=>'CHACAPAMPA','provincia_id'=>103],
['name'=>'CARHUACALLANGA','provincia_id'=>103],
['name'=>'CHICCHE','provincia_id'=>103],
['name'=>'QUICHUAY','provincia_id'=>103],
['name'=>'HUANCAN','provincia_id'=>103],
['name'=>'HUANCAYO','provincia_id'=>103],
['name'=>'INGENIO','provincia_id'=>103],
['name'=>'SICAYA','provincia_id'=>103],
['name'=>'HUALHUAS','provincia_id'=>103],
['name'=>'HUASICANCHA','provincia_id'=>103],
['name'=>'CHONGOS ALTO','provincia_id'=>103],
['name'=>'CULLHUAS','provincia_id'=>103],
['name'=>'HUACRAPUQUIO','provincia_id'=>103],
['name'=>'CHUPURO','provincia_id'=>103],
['name'=>'PILCOMAYO','provincia_id'=>103],
['name'=>'SANTO DOMINGO DE ACOBAMBA','provincia_id'=>103],
['name'=>'PUCARA','provincia_id'=>103],
['name'=>'SAN JERONIMO DE TUNAN','provincia_id'=>103],
['name'=>'QUILCAS','provincia_id'=>103],
['name'=>'COLCA','provincia_id'=>103],
['name'=>'VIQUES','provincia_id'=>103],
['name'=>'HUAYUCACHI','provincia_id'=>103],
['name'=>'CHILCA','provincia_id'=>103],
['name'=>'PACCHA','provincia_id'=>106],
['name'=>'APATA','provincia_id'=>106],
['name'=>'MUQUIYAUYO','provincia_id'=>106],
['name'=>'EL MANTARO','provincia_id'=>106],
['name'=>'HUAMALI','provincia_id'=>106],
['name'=>'ATAURA','provincia_id'=>106],
['name'=>'LLOCLLAPAMPA','provincia_id'=>106],
['name'=>'HUERTAS','provincia_id'=>106],
['name'=>'JULCAN','provincia_id'=>106],
['name'=>'PACA','provincia_id'=>106],
['name'=>'YAULI','provincia_id'=>106],
['name'=>'TUNAN MARCA','provincia_id'=>106],
['name'=>'SINCOS','provincia_id'=>106],
['name'=>'MASMA','provincia_id'=>106],
['name'=>'ACOLLA','provincia_id'=>106],
['name'=>'PARCO','provincia_id'=>106],
['name'=>'CANCHAYLLO','provincia_id'=>106],
['name'=>'JANJAILLO','provincia_id'=>106],
['name'=>'MASMA CHICCHE','provincia_id'=>106],
['name'=>'CURICACA','provincia_id'=>106],
['name'=>'MOLINOS','provincia_id'=>106],
['name'=>'POMACANCHA','provincia_id'=>106],
['name'=>'LEONOR ORDOÑEZ','provincia_id'=>106],
['name'=>'MUQUI','provincia_id'=>106],
['name'=>'HUARIPAMPA','provincia_id'=>106],
['name'=>'SAN LORENZO','provincia_id'=>106],
['name'=>'YAUYOS','provincia_id'=>106],
['name'=>'PANCAN','provincia_id'=>106],
['name'=>'MARCO','provincia_id'=>106],
['name'=>'RICRAN','provincia_id'=>106],
['name'=>'MONOBAMBA','provincia_id'=>106],
['name'=>'SAUSA','provincia_id'=>106],
['name'=>'SAN PEDRO DE CHUNAN','provincia_id'=>106],
['name'=>'JAUJA','provincia_id'=>106],
['name'=>'ULCUMAYO','provincia_id'=>107],
['name'=>'JUNIN','provincia_id'=>107],
['name'=>'ONDORES','provincia_id'=>107],
['name'=>'CARHUAMAYO','provincia_id'=>107],
['name'=>'PAMPA HERMOSA','provincia_id'=>108],
['name'=>'COVIRIALI','provincia_id'=>108],
['name'=>'MAZAMARI','provincia_id'=>108],
['name'=>'SATIPO','provincia_id'=>108],
['name'=>'RIO NEGRO','provincia_id'=>108],
['name'=>'VIZCATAN DEL ENE','provincia_id'=>108],
['name'=>'RIO TAMBO','provincia_id'=>108],
['name'=>'LLAYLLA','provincia_id'=>108],
['name'=>'PANGOA','provincia_id'=>108],
['name'=>'HUARICOLCA','provincia_id'=>109],
['name'=>'TAPO','provincia_id'=>109],
['name'=>'HUASAHUASI','provincia_id'=>109],
['name'=>'TARMA','provincia_id'=>109],
['name'=>'LA UNION','provincia_id'=>109],
['name'=>'ACOBAMBA','provincia_id'=>109],
['name'=>'PALCA','provincia_id'=>109],
['name'=>'PALCAMAYO','provincia_id'=>109],
['name'=>'SAN PEDRO DE CAJAS','provincia_id'=>109],
['name'=>'MOROCOCHA','provincia_id'=>110],
['name'=>'HUAY-HUAY','provincia_id'=>110],
['name'=>'LA OROYA','provincia_id'=>110],
['name'=>'MARCAPOMACOCHA','provincia_id'=>110],
['name'=>'SUITUCANCHA','provincia_id'=>110],
['name'=>'CHACAPALPA','provincia_id'=>110],
['name'=>'YAULI','provincia_id'=>110],
['name'=>'SANTA ROSA DE SACCO','provincia_id'=>110],
['name'=>'PACCHA','provincia_id'=>110],
['name'=>'SANTA BARBARA DE CARHUACAYAN','provincia_id'=>110],
['name'=>'SANTIAGO DE CAO','provincia_id'=>113],
['name'=>'ASCOPE','provincia_id'=>113],
['name'=>'CHICAMA','provincia_id'=>113],
['name'=>'PAIJAN','provincia_id'=>113],
['name'=>'CASA GRANDE','provincia_id'=>113],
['name'=>'CHOCOPE','provincia_id'=>113],
['name'=>'MAGDALENA DE CAO','provincia_id'=>113],
['name'=>'RAZURI','provincia_id'=>113],
['name'=>'BOLIVAR','provincia_id'=>114],
['name'=>'CONDORMARCA','provincia_id'=>114],
['name'=>'LONGOTEA','provincia_id'=>114],
['name'=>'UCUNCHA','provincia_id'=>114],
['name'=>'BAMBAMARCA','provincia_id'=>114],
['name'=>'UCHUMARCA','provincia_id'=>114],
['name'=>'PACANGA','provincia_id'=>115],
['name'=>'CHEPEN','provincia_id'=>115],
['name'=>'PUEBLO NUEVO','provincia_id'=>115],
['name'=>'LUCMA','provincia_id'=>123],
['name'=>'CASCAS','provincia_id'=>123],
['name'=>'MARMOT','provincia_id'=>123],
['name'=>'SAYAPULLO','provincia_id'=>123],
['name'=>'JULCAN','provincia_id'=>117],
['name'=>'CALAMARCA','provincia_id'=>117],
['name'=>'CARABAMBA','provincia_id'=>117],
['name'=>'HUASO','provincia_id'=>117],
['name'=>'AGALLPAMPA','provincia_id'=>118],
['name'=>'LA CUESTA','provincia_id'=>118],
['name'=>'USQUIL','provincia_id'=>118],
['name'=>'OTUZCO','provincia_id'=>118],
['name'=>'HUARANCHAL','provincia_id'=>118],
['name'=>'SALPO','provincia_id'=>118],
['name'=>'CHARAT','provincia_id'=>118],
['name'=>'MACHE','provincia_id'=>118],
['name'=>'PARANDAY','provincia_id'=>118],
['name'=>'SINSICAP','provincia_id'=>118],
['name'=>'GUADALUPE','provincia_id'=>119],
['name'=>'JEQUETEPEQUE','provincia_id'=>119],
['name'=>'SAN JOSE','provincia_id'=>119],
['name'=>'SAN PEDRO DE LLOC','provincia_id'=>119],
['name'=>'PACASMAYO','provincia_id'=>119],
['name'=>'ONGON','provincia_id'=>120],
['name'=>'PATAZ','provincia_id'=>120],
['name'=>'BULDIBUYO','provincia_id'=>120],
['name'=>'CHILLIA','provincia_id'=>120],
['name'=>'HUANCASPATA','provincia_id'=>120],
['name'=>'TAYABAMBA','provincia_id'=>120],
['name'=>'HUAYLILLAS','provincia_id'=>120],
['name'=>'HUAYO','provincia_id'=>120],
['name'=>'URPAY','provincia_id'=>120],
['name'=>'PARCOY','provincia_id'=>120],
['name'=>'PIAS','provincia_id'=>120],
['name'=>'SANTIAGO DE CHALLAS','provincia_id'=>120],
['name'=>'TAURIJA','provincia_id'=>120],
['name'=>'CHUGAY','provincia_id'=>121],
['name'=>'CURGOS','provincia_id'=>121],
['name'=>'SANAGORAN','provincia_id'=>121],
['name'=>'HUAMACHUCO','provincia_id'=>121],
['name'=>'SARIN','provincia_id'=>121],
['name'=>'SARTIMBAMBA','provincia_id'=>121],
['name'=>'COCHORCO','provincia_id'=>121],
['name'=>'MARCABAL','provincia_id'=>121],
['name'=>'ANGASMARCA','provincia_id'=>122],
['name'=>'SITABAMBA','provincia_id'=>122],
['name'=>'MOLLEPATA','provincia_id'=>122],
['name'=>'MOLLEBAMBA','provincia_id'=>122],
['name'=>'SANTIAGO DE CHUCO','provincia_id'=>122],
['name'=>'CACHICADAN','provincia_id'=>122],
['name'=>'SANTA CRUZ DE CHUCA','provincia_id'=>122],
['name'=>'QUIRUVILCA','provincia_id'=>122],
['name'=>'EL PORVENIR','provincia_id'=>112],
['name'=>'VICTOR LARCO HERRERA','provincia_id'=>112],
['name'=>'LA ESPERANZA','provincia_id'=>112],
['name'=>'TRUJILLO','provincia_id'=>112],
['name'=>'HUANCHACO','provincia_id'=>112],
['name'=>'SALAVERRY','provincia_id'=>112],
['name'=>'SIMBAL','provincia_id'=>112],
['name'=>'MOCHE','provincia_id'=>112],
['name'=>'POROTO','provincia_id'=>112],
['name'=>'LAREDO','provincia_id'=>112],
['name'=>'FLORENCIA DE MORA','provincia_id'=>112],
['name'=>'GUADALUPITO','provincia_id'=>124],
['name'=>'VIRU','provincia_id'=>124],
['name'=>'CHAO','provincia_id'=>124],
['name'=>'ETEN','provincia_id'=>125],
['name'=>'SANTA ROSA','provincia_id'=>125],
['name'=>'CHICLAYO','provincia_id'=>125],
['name'=>'CHONGOYAPE','provincia_id'=>125],
['name'=>'OYOTUN','provincia_id'=>125],
['name'=>'TUMAN','provincia_id'=>125],
['name'=>'LAGUNAS','provincia_id'=>125],
['name'=>'MONSEFU','provincia_id'=>125],
['name'=>'CAYALTI','provincia_id'=>125],
['name'=>'ETEN PUERTO','provincia_id'=>125],
['name'=>'JOSE LEONARDO ORTIZ','provincia_id'=>125],
['name'=>'PICSI','provincia_id'=>125],
['name'=>'PIMENTEL','provincia_id'=>125],
['name'=>'POMALCA','provincia_id'=>125],
['name'=>'PUCALA','provincia_id'=>125],
['name'=>'NUEVA ARICA','provincia_id'=>125],
['name'=>'LA VICTORIA','provincia_id'=>125],
['name'=>'SAÑA','provincia_id'=>125],
['name'=>'PATAPO','provincia_id'=>125],
['name'=>'REQUE','provincia_id'=>125],
['name'=>'PITIPO','provincia_id'=>126],
['name'=>'INCAHUASI','provincia_id'=>126],
['name'=>'FERREÑAFE','provincia_id'=>126],
['name'=>'PUEBLO NUEVO','provincia_id'=>126],
['name'=>'CAÑARIS','provincia_id'=>126],
['name'=>'MANUEL ANTONIO MESONES MURO','provincia_id'=>126],
['name'=>'JAYANCA','provincia_id'=>127],
['name'=>'MOTUPE','provincia_id'=>127],
['name'=>'OLMOS','provincia_id'=>127],
['name'=>'ILLIMO','provincia_id'=>127],
['name'=>'PACORA','provincia_id'=>127],
['name'=>'SALAS','provincia_id'=>127],
['name'=>'LAMBAYEQUE','provincia_id'=>127],
['name'=>'MOCHUMI','provincia_id'=>127],
['name'=>'SAN JOSE','provincia_id'=>127],
['name'=>'TUCUME','provincia_id'=>127],
['name'=>'CHOCHOPE','provincia_id'=>127],
['name'=>'MORROPE','provincia_id'=>127],
['name'=>'PARAMONGA','provincia_id'=>129],
['name'=>'SUPE','provincia_id'=>129],
['name'=>'SUPE PUERTO','provincia_id'=>129],
['name'=>'BARRANCA','provincia_id'=>129],
['name'=>'PATIVILCA','provincia_id'=>129],
['name'=>'HUANCAPON','provincia_id'=>130],
['name'=>'MANAS','provincia_id'=>130],
['name'=>'CAJATAMBO','provincia_id'=>130],
['name'=>'COPA','provincia_id'=>130],
['name'=>'GORGOR','provincia_id'=>130],
['name'=>'CANTA','provincia_id'=>131],
['name'=>'LACHAQUI','provincia_id'=>131],
['name'=>'HUAROS','provincia_id'=>131],
['name'=>'ARAHUAY','provincia_id'=>131],
['name'=>'HUAMANTANGA','provincia_id'=>131],
['name'=>'SAN BUENAVENTURA','provincia_id'=>131],
['name'=>'SANTA ROSA DE QUIVES','provincia_id'=>131],
['name'=>'IMPERIAL','provincia_id'=>132],
['name'=>'SANTA CRUZ DE FLORES','provincia_id'=>132],
['name'=>'CALANGO','provincia_id'=>132],
['name'=>'CERRO AZUL','provincia_id'=>132],
['name'=>'COAYLLO','provincia_id'=>132],
['name'=>'NUEVO IMPERIAL','provincia_id'=>132],
['name'=>'SAN ANTONIO','provincia_id'=>132],
['name'=>'SAN LUIS','provincia_id'=>132],
['name'=>'ASIA','provincia_id'=>132],
['name'=>'QUILMANA','provincia_id'=>132],
['name'=>'CHILCA','provincia_id'=>132],
['name'=>'MALA','provincia_id'=>132],
['name'=>'LUNAHUANA','provincia_id'=>132],
['name'=>'PACARAN','provincia_id'=>132],
['name'=>'ZUÑIGA','provincia_id'=>132],
['name'=>'SAN VICENTE DE CAÑETE','provincia_id'=>132],
['name'=>'PACARAOS','provincia_id'=>133],
['name'=>'ATAVILLOS ALTO','provincia_id'=>133],
['name'=>'AUCALLAMA','provincia_id'=>133],
['name'=>'LAMPIAN','provincia_id'=>133],
['name'=>'SAN MIGUEL DE ACOS','provincia_id'=>133],
['name'=>'SANTA CRUZ DE ANDAMARCA','provincia_id'=>133],
['name'=>'HUARAL','provincia_id'=>133],
['name'=>'CHANCAY','provincia_id'=>133],
['name'=>'SUMBILCA','provincia_id'=>133],
['name'=>'ATAVILLOS BAJO','provincia_id'=>133],
['name'=>'VEINTISIETE DE NOVIEMBRE','provincia_id'=>133],
['name'=>'IHUARI','provincia_id'=>133],
['name'=>'CARAMPOMA','provincia_id'=>134],
['name'=>'CHICLA','provincia_id'=>134],
['name'=>'HUACHUPAMPA','provincia_id'=>134],
['name'=>'LAHUAYTAMBO','provincia_id'=>134],
['name'=>'RICARDO PALMA','provincia_id'=>134],
['name'=>'SAN MATEO DE OTAO','provincia_id'=>134],
['name'=>'SANGALLAYA','provincia_id'=>134],
['name'=>'SANTIAGO DE ANCHUCAYA','provincia_id'=>134],
['name'=>'SANTO DOMINGO DE LOS OLLEROS','provincia_id'=>134],
['name'=>'ANTIOQUIA','provincia_id'=>134],
['name'=>'CALLAHUANCA','provincia_id'=>134],
['name'=>'HUAROCHIRI','provincia_id'=>134],
['name'=>'MARIATANA','provincia_id'=>134],
['name'=>'SAN BARTOLOME','provincia_id'=>134],
['name'=>'SAN JUAN DE IRIS','provincia_id'=>134],
['name'=>'SAN MATEO','provincia_id'=>134],
['name'=>'SAN PEDRO DE HUANCAYRE','provincia_id'=>134],
['name'=>'SANTIAGO DE TUNA','provincia_id'=>134],
['name'=>'MATUCANA','provincia_id'=>134],
['name'=>'CUENCA','provincia_id'=>134],
['name'=>'HUANZA','provincia_id'=>134],
['name'=>'LANGA','provincia_id'=>134],
['name'=>'LARAOS','provincia_id'=>134],
['name'=>'SAN ANDRES DE TUPICOCHA','provincia_id'=>134],
['name'=>'SAN ANTONIO','provincia_id'=>134],
['name'=>'SAN DAMIAN','provincia_id'=>134],
['name'=>'SAN JUAN DE TANTARANCHE','provincia_id'=>134],
['name'=>'SAN LORENZO DE QUINTI','provincia_id'=>134],
['name'=>'SAN PEDRO DE CASTA','provincia_id'=>134],
['name'=>'SANTA CRUZ DE COCACHACRA','provincia_id'=>134],
['name'=>'SANTA EULALIA','provincia_id'=>134],
['name'=>'SURCO','provincia_id'=>134],
['name'=>'LEONCIO PRADO','provincia_id'=>133],
['name'=>'CHECRAS','provincia_id'=>133],
['name'=>'SANTA LEONOR','provincia_id'=>133],
['name'=>'HUACHO','provincia_id'=>133],
['name'=>'CALETA DE CARQUIN','provincia_id'=>133],
['name'=>'SANTA MARIA','provincia_id'=>133],
['name'=>'HUAURA','provincia_id'=>133],
['name'=>'AMBAR','provincia_id'=>133],
['name'=>'HUALMAY','provincia_id'=>133],
['name'=>'PACCHO','provincia_id'=>133],
['name'=>'SAYAN','provincia_id'=>133],
['name'=>'VEGUETA','provincia_id'=>133],
['name'=>'LURIGANCHO','provincia_id'=>128],
['name'=>'SAN BORJA','provincia_id'=>128],
['name'=>'SAN MIGUEL','provincia_id'=>128],
['name'=>'RIMAC','provincia_id'=>128],
['name'=>'INDEPENDENCIA','provincia_id'=>128],
['name'=>'SAN ISIDRO','provincia_id'=>128],
['name'=>'BARRANCO','provincia_id'=>128],
['name'=>'PUENTE PIEDRA','provincia_id'=>128],
['name'=>'SAN MARTIN DE PORRES','provincia_id'=>128],
['name'=>'COMAS','provincia_id'=>128],
['name'=>'LA MOLINA','provincia_id'=>128],
['name'=>'PACHACAMAC','provincia_id'=>128],
['name'=>'PUNTA HERMOSA','provincia_id'=>128],
['name'=>'SANTA MARIA DEL MAR','provincia_id'=>128],
['name'=>'SAN BARTOLO','provincia_id'=>128],
['name'=>'LIMA','provincia_id'=>128],
['name'=>'MIRAFLORES','provincia_id'=>128],
['name'=>'MAGDALENA DEL MAR','provincia_id'=>128],
['name'=>'SAN LUIS','provincia_id'=>128],
['name'=>'SANTA ANITA','provincia_id'=>128],
['name'=>'SURQUILLO','provincia_id'=>128],
['name'=>'BREÑA','provincia_id'=>128],
['name'=>'SANTA ROSA','provincia_id'=>128],
['name'=>'SAN JUAN DE MIRAFLORES','provincia_id'=>128],
['name'=>'SANTIAGO DE SURCO','provincia_id'=>128],
['name'=>'VILLA EL SALVADOR','provincia_id'=>128],
['name'=>'EL AGUSTINO','provincia_id'=>128],
['name'=>'LOS OLIVOS','provincia_id'=>128],
['name'=>'CARABAYLLO','provincia_id'=>128],
['name'=>'PUCUSANA','provincia_id'=>128],
['name'=>'PUNTA NEGRA','provincia_id'=>128],
['name'=>'JESUS MARIA','provincia_id'=>128],
['name'=>'LINCE','provincia_id'=>128],
['name'=>'PUEBLO LIBRE','provincia_id'=>128],
['name'=>'SAN JUAN DE LURIGANCHO','provincia_id'=>128],
['name'=>'LA VICTORIA','provincia_id'=>128],
['name'=>'ANCON','provincia_id'=>128],
['name'=>'ATE','provincia_id'=>128],
['name'=>'CHACLACAYO','provincia_id'=>128],
['name'=>'VILLA MARIA DEL TRIUNFO','provincia_id'=>128],
['name'=>'CIENEGUILLA','provincia_id'=>128],
['name'=>'LURIN','provincia_id'=>128],
['name'=>'CHORRILLOS','provincia_id'=>128],
['name'=>'SANTA MARIA DE HUACHIPA /1','provincia_id'=>128],
['name'=>'CAUJUL','provincia_id'=>136],
['name'=>'COCHAMARCA','provincia_id'=>136],
['name'=>'ANDAJES','provincia_id'=>136],
['name'=>'NAVAN','provincia_id'=>136],
['name'=>'OYON','provincia_id'=>136],
['name'=>'PACHANGARA','provincia_id'=>136],
['name'=>'YAUYOS','provincia_id'=>137],
['name'=>'ALIS','provincia_id'=>137],
['name'=>'ALLAUCA','provincia_id'=>137],
['name'=>'HUAÑEC','provincia_id'=>137],
['name'=>'MADEAN','provincia_id'=>137],
['name'=>'QUINCHES','provincia_id'=>137],
['name'=>'TAURIPAMPA','provincia_id'=>137],
['name'=>'CATAHUASI','provincia_id'=>137],
['name'=>'CHOCOS','provincia_id'=>137],
['name'=>'HUANGASCAR','provincia_id'=>137],
['name'=>'LINCHA','provincia_id'=>137],
['name'=>'PUTINZA','provincia_id'=>137],
['name'=>'AZANGARO','provincia_id'=>137],
['name'=>'CARANIA','provincia_id'=>137],
['name'=>'HUAMPARA','provincia_id'=>137],
['name'=>'HUANCAYA','provincia_id'=>137],
['name'=>'HUANTAN','provincia_id'=>137],
['name'=>'LARAOS','provincia_id'=>137],
['name'=>'MIRAFLORES','provincia_id'=>137],
['name'=>'OMAS','provincia_id'=>137],
['name'=>'QUINOCAY','provincia_id'=>137],
['name'=>'SAN PEDRO DE PILAS','provincia_id'=>137],
['name'=>'VITIS','provincia_id'=>137],
['name'=>'HONGOS','provincia_id'=>137],
['name'=>'TUPE','provincia_id'=>137],
['name'=>'VIÑAC','provincia_id'=>137],
['name'=>'CACRA','provincia_id'=>137],
['name'=>'AYAVIRI','provincia_id'=>137],
['name'=>'COCHAS','provincia_id'=>137],
['name'=>'SAN JOAQUIN','provincia_id'=>137],
['name'=>'TANTA','provincia_id'=>137],
['name'=>'TOMAS','provincia_id'=>137],
['name'=>'COLONIA','provincia_id'=>137],
['name'=>'LAGUNAS','provincia_id'=>139],
['name'=>'SANTA CRUZ','provincia_id'=>139],
['name'=>'BALSAPUERTO','provincia_id'=>139],
['name'=>'YURIMAGUAS','provincia_id'=>139],
['name'=>'JEBEROS','provincia_id'=>139],
['name'=>'TENIENTE CESAR LOPEZ ROJAS','provincia_id'=>139],
['name'=>'BARRANCA','provincia_id'=>144],
['name'=>'MANSERICHE','provincia_id'=>144],
['name'=>'CAHUAPANAS','provincia_id'=>144],
['name'=>'MORONA','provincia_id'=>144],
['name'=>'PASTAZA','provincia_id'=>144],
['name'=>'ANDOAS','provincia_id'=>144],
['name'=>'NAUTA','provincia_id'=>140],
['name'=>'TIGRE','provincia_id'=>140],
['name'=>'URARINAS','provincia_id'=>140],
['name'=>'PARINARI','provincia_id'=>140],
['name'=>'TROMPETEROS','provincia_id'=>140],
['name'=>'RAMON CASTILLA','provincia_id'=>141],
['name'=>'PEBAS','provincia_id'=>141],
['name'=>'YAVARI','provincia_id'=>141],
['name'=>'SAN PABLO','provincia_id'=>141],
['name'=>'IQUITOS','provincia_id'=>138],
['name'=>'FERNANDO LORES','provincia_id'=>138],
['name'=>'MAZAN','provincia_id'=>138],
['name'=>'TORRES CAUSANA','provincia_id'=>138],
['name'=>'BELEN','provincia_id'=>138],
['name'=>'ALTO NANAY','provincia_id'=>138],
['name'=>'INDIANA','provincia_id'=>138],
['name'=>'LAS AMAZONAS','provincia_id'=>138],
['name'=>'NAPO','provincia_id'=>138],
['name'=>'PUNCHANA','provincia_id'=>138],
['name'=>'SAN JUAN BAUTISTA','provincia_id'=>138],
['name'=>'YAGUAS','provincia_id'=>145],
['name'=>'ROSA PANDURO','provincia_id'=>145],
['name'=>'PUTUMAYO','provincia_id'=>145],
['name'=>'TENIENTE MANUEL CLAVERO','provincia_id'=>145],
['name'=>'CAPELO','provincia_id'=>142],
['name'=>'SAQUENA','provincia_id'=>142],
['name'=>'MAQUIA','provincia_id'=>142],
['name'=>'SOPLIN','provincia_id'=>142],
['name'=>'YAQUERANA','provincia_id'=>142],
['name'=>'ALTO TAPICHE','provincia_id'=>142],
['name'=>'EMILIO SAN MARTIN','provincia_id'=>142],
['name'=>'PUINAHUA','provincia_id'=>142],
['name'=>'REQUENA','provincia_id'=>142],
['name'=>'TAPICHE','provincia_id'=>142],
['name'=>'JENARO HERRERA','provincia_id'=>142],
['name'=>'CONTAMANA','provincia_id'=>143],
['name'=>'PADRE MARQUEZ','provincia_id'=>143],
['name'=>'SARAYACU','provincia_id'=>143],
['name'=>'INAHUAYA','provincia_id'=>143],
['name'=>'VARGAS GUERRA','provincia_id'=>143],
['name'=>'PAMPA HERMOSA','provincia_id'=>143],
['name'=>'HUEPETUHE','provincia_id'=>147],
['name'=>'MANU','provincia_id'=>147],
['name'=>'MADRE DE DIOS','provincia_id'=>147],
['name'=>'FITZCARRALD','provincia_id'=>147],
['name'=>'IÑAPARI','provincia_id'=>148],
['name'=>'TAHUAMANU','provincia_id'=>148],
['name'=>'IBERIA','provincia_id'=>148],
['name'=>'INAMBARI','provincia_id'=>148],
['name'=>'LABERINTO','provincia_id'=>148],
['name'=>'LAS PIEDRAS','provincia_id'=>148],
['name'=>'TAMBOPATA','provincia_id'=>148],
['name'=>'COALAQUE','provincia_id'=>150],
['name'=>'LA CAPILLA','provincia_id'=>150],
['name'=>'LLOQUE','provincia_id'=>150],
['name'=>'PUQUINA','provincia_id'=>150],
['name'=>'QUINISTAQUILLAS','provincia_id'=>150],
['name'=>'OMATE','provincia_id'=>150],
['name'=>'CHOJATA','provincia_id'=>150],
['name'=>'ICHUÑA','provincia_id'=>150],
['name'=>'MATALAQUE','provincia_id'=>150],
['name'=>'UBINAS','provincia_id'=>150],
['name'=>'YUNGA','provincia_id'=>150],
['name'=>'ILO','provincia_id'=>151],
['name'=>'EL ALGARROBAL','provincia_id'=>151],
['name'=>'PACOCHA','provincia_id'=>151],
['name'=>'MOQUEGUA','provincia_id'=>149],
['name'=>'SAMEGUA','provincia_id'=>149],
['name'=>'SAN CRISTOBAL','provincia_id'=>149],
['name'=>'TORATA','provincia_id'=>149],
['name'=>'CARUMAS','provincia_id'=>149],
['name'=>'CUCHUMBAYA','provincia_id'=>149],
['name'=>'SAN PEDRO DE PILLAO','provincia_id'=>153],
['name'=>'CHACAYAN','provincia_id'=>153],
['name'=>'PAUCAR','provincia_id'=>153],
['name'=>'VILCABAMBA','provincia_id'=>153],
['name'=>'YANAHUANCA','provincia_id'=>153],
['name'=>'GOYLLARISQUIZGA','provincia_id'=>153],
['name'=>'TAPUC','provincia_id'=>153],
['name'=>'SANTA ANA DE TUSI','provincia_id'=>153],
['name'=>'PUERTO BERMUDEZ','provincia_id'=>154],
['name'=>'CONSTITUCION','provincia_id'=>154],
['name'=>'OXAPAMPA','provincia_id'=>154],
['name'=>'VILLA RICA','provincia_id'=>154],
['name'=>'HUANCABAMBA','provincia_id'=>154],
['name'=>'POZUZO','provincia_id'=>154],
['name'=>'CHONTABAMBA','provincia_id'=>154],
['name'=>'PALCAZU','provincia_id'=>154],
['name'=>'HUAYLLAY','provincia_id'=>152],
['name'=>'TINYAHUARCO','provincia_id'=>152],
['name'=>'SIMON BOLIVAR','provincia_id'=>152],
['name'=>'TICLACAYAN','provincia_id'=>152],
['name'=>'HUARIACA','provincia_id'=>152],
['name'=>'CHAUPIMARCA','provincia_id'=>152],
['name'=>'SAN FRANCISCO DE ASIS DE YARUSYACAN','provincia_id'=>152],
['name'=>'VICCO','provincia_id'=>152],
['name'=>'NINACACA','provincia_id'=>152],
['name'=>'PAUCARTAMBO','provincia_id'=>152],
['name'=>'YANACANCHA','provincia_id'=>152],
['name'=>'PALLANCHACRA','provincia_id'=>152],
['name'=>'HUACHON','provincia_id'=>152],
['name'=>'PACAIPAMPA','provincia_id'=>156],
['name'=>'FRIAS','provincia_id'=>156],
['name'=>'LAGUNAS','provincia_id'=>156],
['name'=>'AYABACA','provincia_id'=>156],
['name'=>'SUYO','provincia_id'=>156],
['name'=>'PAIMAS','provincia_id'=>156],
['name'=>'MONTERO','provincia_id'=>156],
['name'=>'SAPILLICA','provincia_id'=>156],
['name'=>'JILILI','provincia_id'=>156],
['name'=>'SICCHEZ','provincia_id'=>156],
['name'=>'HUANCABAMBA','provincia_id'=>157],
['name'=>'CANCHAQUE','provincia_id'=>157],
['name'=>'SONDORILLO','provincia_id'=>157],
['name'=>'SONDOR','provincia_id'=>157],
['name'=>'EL CARMEN DE LA FRONTERA','provincia_id'=>157],
['name'=>'LALAQUIZ','provincia_id'=>157],
['name'=>'HUARMACA','provincia_id'=>157],
['name'=>'SAN MIGUEL DE EL FAIQUE','provincia_id'=>157],
['name'=>'LA MATANZA','provincia_id'=>158],
['name'=>'SANTO DOMINGO','provincia_id'=>158],
['name'=>'CHALACO','provincia_id'=>158],
['name'=>'BUENOS AIRES','provincia_id'=>158],
['name'=>'MORROPON','provincia_id'=>158],
['name'=>'YAMANGO','provincia_id'=>158],
['name'=>'CHULUCANAS','provincia_id'=>158],
['name'=>'SALITRAL','provincia_id'=>158],
['name'=>'SAN JUAN DE BIGOTE','provincia_id'=>158],
['name'=>'SANTA CATALINA DE MOSSA','provincia_id'=>158],
['name'=>'AMOTAPE','provincia_id'=>159],
['name'=>'COLAN','provincia_id'=>159],
['name'=>'TAMARINDO','provincia_id'=>159],
['name'=>'LA HUACA','provincia_id'=>159],
['name'=>'PAITA','provincia_id'=>159],
['name'=>'VICHAYAL','provincia_id'=>159],
['name'=>'ARENAL','provincia_id'=>159],
['name'=>'CATACAOS','provincia_id'=>155],
['name'=>'PIURA','provincia_id'=>155],
['name'=>'LAS LOMAS','provincia_id'=>155],
['name'=>'EL TALLAN','provincia_id'=>155],
['name'=>'CURA MORI','provincia_id'=>155],
['name'=>'LA UNION','provincia_id'=>155],
['name'=>'TAMBO GRANDE','provincia_id'=>155],
['name'=>'LA ARENA','provincia_id'=>155],
['name'=>'CASTILLA','provincia_id'=>155],
['name'=>'VEINTISEIS DE OCTUBRE','provincia_id'=>155],
['name'=>'BERNAL','provincia_id'=>162],
['name'=>'SECHURA','provincia_id'=>162],
['name'=>'CRISTO NOS VALGA','provincia_id'=>162],
['name'=>'RINCONADA LLICUAR','provincia_id'=>162],
['name'=>'BELLAVISTA DE LA UNION','provincia_id'=>162],
['name'=>'VICE','provincia_id'=>162],
['name'=>'IGNACIO ESCUDERO','provincia_id'=>160],
['name'=>'MARCAVELICA','provincia_id'=>160],
['name'=>'LANCONES','provincia_id'=>160],
['name'=>'BELLAVISTA','provincia_id'=>160],
['name'=>'SALITRAL','provincia_id'=>160],
['name'=>'MIGUEL CHECA','provincia_id'=>160],
['name'=>'SULLANA','provincia_id'=>160],
['name'=>'QUERECOTILLO','provincia_id'=>160],
['name'=>'PARIÑAS','provincia_id'=>161],
['name'=>'LOBITOS','provincia_id'=>161],
['name'=>'MANCORA','provincia_id'=>161],
['name'=>'LA BREA','provincia_id'=>161],
['name'=>'LOS ORGANOS','provincia_id'=>161],
['name'=>'EL ALTO','provincia_id'=>161],
['name'=>'SAMAN','provincia_id'=>164],
['name'=>'ARAPA','provincia_id'=>164],
['name'=>'MUÑANI','provincia_id'=>164],
['name'=>'ACHAYA','provincia_id'=>164],
['name'=>'CAMINACA','provincia_id'=>164],
['name'=>'CHUPA','provincia_id'=>164],
['name'=>'SANTIAGO DE PUPUJA','provincia_id'=>164],
['name'=>'SAN JUAN DE SALINAS','provincia_id'=>164],
['name'=>'POTONI','provincia_id'=>164],
['name'=>'JOSE DOMINGO CHOQUEHUANCA','provincia_id'=>164],
['name'=>'TIRAPATA','provincia_id'=>164],
['name'=>'AZANGARO','provincia_id'=>164],
['name'=>'ASILLO','provincia_id'=>164],
['name'=>'SAN ANTON','provincia_id'=>164],
['name'=>'SAN JOSE','provincia_id'=>164],
['name'=>'AJOYANI','provincia_id'=>165],
['name'=>'OLLACHEA','provincia_id'=>165],
['name'=>'CRUCERO','provincia_id'=>165],
['name'=>'USICAYOS','provincia_id'=>165],
['name'=>'MACUSANI','provincia_id'=>165],
['name'=>'CORANI','provincia_id'=>165],
['name'=>'ITUATA','provincia_id'=>165],
['name'=>'COASA','provincia_id'=>165],
['name'=>'AYAPATA','provincia_id'=>165],
['name'=>'SAN GABAN','provincia_id'=>165],
['name'=>'PISACOMA','provincia_id'=>166],
['name'=>'JULI','provincia_id'=>166],
['name'=>'HUACULLANI','provincia_id'=>166],
['name'=>'ZEPITA','provincia_id'=>166],
['name'=>'KELLUYO','provincia_id'=>166],
['name'=>'DESAGUADERO','provincia_id'=>166],
['name'=>'POMATA','provincia_id'=>166],
['name'=>'CAPAZO','provincia_id'=>167],
['name'=>'SANTA ROSA','provincia_id'=>167],
['name'=>'CONDURIRI','provincia_id'=>167],
['name'=>'PILCUYO','provincia_id'=>167],
['name'=>'ILAVE','provincia_id'=>167],
['name'=>'TARACO','provincia_id'=>168],
['name'=>'PUSI','provincia_id'=>168],
['name'=>'VILQUE CHICO','provincia_id'=>168],
['name'=>'HUATASANI','provincia_id'=>168],
['name'=>'ROSASPATA','provincia_id'=>168],
['name'=>'HUANCANE','provincia_id'=>168],
['name'=>'COJATA','provincia_id'=>168],
['name'=>'INCHUPALLA','provincia_id'=>168],
['name'=>'LAMPA','provincia_id'=>169],
['name'=>'CABANILLA','provincia_id'=>169],
['name'=>'OCUVIRI','provincia_id'=>169],
['name'=>'CALAPUJA','provincia_id'=>169],
['name'=>'SANTA LUCIA','provincia_id'=>169],
['name'=>'PARATIA','provincia_id'=>169],
['name'=>'PUCARA','provincia_id'=>169],
['name'=>'NICASIO','provincia_id'=>169],
['name'=>'PALCA','provincia_id'=>169],
['name'=>'VILAVILA','provincia_id'=>169],
['name'=>'AYAVIRI','provincia_id'=>170],
['name'=>'ORURILLO','provincia_id'=>170],
['name'=>'NUÑOA','provincia_id'=>170],
['name'=>'SANTA ROSA','provincia_id'=>170],
['name'=>'UMACHIRI','provincia_id'=>170],
['name'=>'CUPI','provincia_id'=>170],
['name'=>'ANTAUTA','provincia_id'=>170],
['name'=>'LLALLI','provincia_id'=>170],
['name'=>'MACARI','provincia_id'=>170],
['name'=>'TILALI','provincia_id'=>171],
['name'=>'HUAYRAPATA','provincia_id'=>171],
['name'=>'CONIMA','provincia_id'=>171],
['name'=>'MOHO','provincia_id'=>171],
['name'=>'PUNO','provincia_id'=>163],
['name'=>'PAUCARCOLLA','provincia_id'=>163],
['name'=>'VILQUE','provincia_id'=>163],
['name'=>'AMANTANI','provincia_id'=>163],
['name'=>'ACORA','provincia_id'=>163],
['name'=>'CHUCUITO','provincia_id'=>163],
['name'=>'MAÑAZO','provincia_id'=>163],
['name'=>'HUATA','provincia_id'=>163],
['name'=>'SAN ANTONIO','provincia_id'=>163],
['name'=>'TIQUILLACA','provincia_id'=>163],
['name'=>'ATUNCOLLA','provincia_id'=>163],
['name'=>'COATA','provincia_id'=>163],
['name'=>'CAPACHICA','provincia_id'=>163],
['name'=>'PICHACANI','provincia_id'=>163],
['name'=>'PLATERIA','provincia_id'=>163],
['name'=>'QUILCAPUNCU','provincia_id'=>172],
['name'=>'PEDRO VILCA APAZA','provincia_id'=>172],
['name'=>'PUTINA','provincia_id'=>172],
['name'=>'ANANEA','provincia_id'=>172],
['name'=>'SINA','provincia_id'=>172],
['name'=>'CABANILLAS','provincia_id'=>173],
['name'=>'JULIACA','provincia_id'=>173],
['name'=>'SAN MIGUEL','provincia_id'=>173],
['name'=>'CABANA','provincia_id'=>173],
['name'=>'CARACOTO','provincia_id'=>173],
['name'=>'PATAMBUCO','provincia_id'=>174],
['name'=>'SANDIA','provincia_id'=>174],
['name'=>'QUIACA','provincia_id'=>174],
['name'=>'ALTO INAMBARI','provincia_id'=>174],
['name'=>'CUYOCUYO','provincia_id'=>174],
['name'=>'YANAHUAYA','provincia_id'=>174],
['name'=>'SAN JUAN DEL ORO','provincia_id'=>174],
['name'=>'PHARA','provincia_id'=>174],
['name'=>'LIMBANI','provincia_id'=>174],
['name'=>'SAN PEDRO DE PUTINA PUNCO','provincia_id'=>174],
['name'=>'ANAPIA','provincia_id'=>175],
['name'=>'YUNGUYO','provincia_id'=>175],
['name'=>'TINICACHI','provincia_id'=>175],
['name'=>'CUTURAPI','provincia_id'=>175],
['name'=>'COPANI','provincia_id'=>175],
['name'=>'UNICACHI','provincia_id'=>175],
['name'=>'OLLARAYA','provincia_id'=>175],
['name'=>'BAJO BIAVO','provincia_id'=>177],
['name'=>'HUALLAGA','provincia_id'=>177],
['name'=>'SAN RAFAEL','provincia_id'=>177],
['name'=>'ALTO BIAVO','provincia_id'=>177],
['name'=>'BELLAVISTA','provincia_id'=>177],
['name'=>'SAN PABLO','provincia_id'=>177],
['name'=>'SANTA ROSA','provincia_id'=>178],
['name'=>'AGUA BLANCA','provincia_id'=>178],
['name'=>'SHATOJA','provincia_id'=>178],
['name'=>'SAN JOSE DE SISA','provincia_id'=>178],
['name'=>'SAN MARTIN','provincia_id'=>178],
['name'=>'SACANCHE','provincia_id'=>179],
['name'=>'ALTO SAPOSOA','provincia_id'=>179],
['name'=>'TINGO DE SAPOSOA','provincia_id'=>179],
['name'=>'EL ESLABON','provincia_id'=>179],
['name'=>'SAPOSOA','provincia_id'=>179],
['name'=>'PISCOYACU','provincia_id'=>179],
['name'=>'ZAPATERO','provincia_id'=>182],
['name'=>'CUÑUMBUQUI','provincia_id'=>182],
['name'=>'CAYNARACHI','provincia_id'=>182],
['name'=>'BARRANQUITA','provincia_id'=>182],
['name'=>'LAMAS','provincia_id'=>182],
['name'=>'SHANAO','provincia_id'=>182],
['name'=>'TABALOSOS','provincia_id'=>182],
['name'=>'ALONSO DE ALVARADO','provincia_id'=>182],
['name'=>'PINTO RECODO','provincia_id'=>182],
['name'=>'SAN ROQUE DE CUMBAZA','provincia_id'=>182],
['name'=>'RUMISAPA','provincia_id'=>182],
['name'=>'PAJARILLO','provincia_id'=>183],
['name'=>'JUANJUI','provincia_id'=>183],
['name'=>'CAMPANILLA','provincia_id'=>183],
['name'=>'HUICUNGO','provincia_id'=>183],
['name'=>'PACHIZA','provincia_id'=>183],
['name'=>'JEPELACIO','provincia_id'=>176],
['name'=>'CALZADA','provincia_id'=>176],
['name'=>'HABANA','provincia_id'=>176],
['name'=>'SORITOR','provincia_id'=>176],
['name'=>'MOYOBAMBA','provincia_id'=>176],
['name'=>'YANTALO','provincia_id'=>176],
['name'=>'CASPISAPA','provincia_id'=>184],
['name'=>'SAN HILARION','provincia_id'=>184],
['name'=>'SHAMBOYACU','provincia_id'=>184],
['name'=>'TINGO DE PONASA','provincia_id'=>184],
['name'=>'PICOTA','provincia_id'=>184],
['name'=>'BUENOS AIRES','provincia_id'=>184],
['name'=>'SAN CRISTOBAL','provincia_id'=>184],
['name'=>'PILLUANA','provincia_id'=>184],
['name'=>'TRES UNIDOS','provincia_id'=>184],
['name'=>'PUCACACA','provincia_id'=>184],
['name'=>'YORONGOS','provincia_id'=>185],
['name'=>'SAN FERNANDO','provincia_id'=>185],
['name'=>'PARDO MIGUEL','provincia_id'=>185],
['name'=>'RIOJA','provincia_id'=>185],
['name'=>'ELIAS SOPLIN VARGAS','provincia_id'=>185],
['name'=>'NUEVA CAJAMARCA','provincia_id'=>185],
['name'=>'POSIC','provincia_id'=>185],
['name'=>'YURACYACU','provincia_id'=>185],
['name'=>'AWAJUN','provincia_id'=>185],
['name'=>'ALBERTO LEVEAU','provincia_id'=>186],
['name'=>'CHAZUTA','provincia_id'=>186],
['name'=>'CACATACHI','provincia_id'=>186],
['name'=>'HUIMBAYOC','provincia_id'=>186],
['name'=>'EL PORVENIR','provincia_id'=>186],
['name'=>'JUAN GUERRA','provincia_id'=>186],
['name'=>'LA BANDA DE SHILCAYO','provincia_id'=>186],
['name'=>'MORALES','provincia_id'=>186],
['name'=>'SAN ANTONIO','provincia_id'=>186],
['name'=>'SAUCE','provincia_id'=>186],
['name'=>'SHAPAJA','provincia_id'=>186],
['name'=>'TARAPOTO','provincia_id'=>186],
['name'=>'CHIPURANA','provincia_id'=>186],
['name'=>'PAPAPLAYA','provincia_id'=>186],
['name'=>'NUEVO PROGRESO','provincia_id'=>187],
['name'=>'POLVORA','provincia_id'=>187],
['name'=>'UCHIZA','provincia_id'=>187],
['name'=>'TOCACHE','provincia_id'=>187],
['name'=>'SHUNTE','provincia_id'=>187],
['name'=>'CAMILACA','provincia_id'=>189],
['name'=>'CANDARAVE','provincia_id'=>189],
['name'=>'CURIBAYA','provincia_id'=>189],
['name'=>'CAIRANI','provincia_id'=>189],
['name'=>'HUANUARA','provincia_id'=>189],
['name'=>'QUILAHUANI','provincia_id'=>189],
['name'=>'LOCUMBA','provincia_id'=>190],
['name'=>'ILABAYA','provincia_id'=>190],
['name'=>'ITE','provincia_id'=>190],
['name'=>'TACNA','provincia_id'=>188],
['name'=>'CALANA','provincia_id'=>188],
['name'=>'PACHIA','provincia_id'=>188],
['name'=>'PALCA','provincia_id'=>188],
['name'=>'POCOLLAY','provincia_id'=>188],
['name'=>'CIUDAD NUEVA','provincia_id'=>188],
['name'=>'LA YARADA LOS PALOS','provincia_id'=>188],
['name'=>'SAMA','provincia_id'=>188],
['name'=>'ALTO DE LA ALIANZA','provincia_id'=>188],
['name'=>'INCLAN','provincia_id'=>188],
['name'=>'CORONEL GREGORIO ALBARRACIN LANCHIPA','provincia_id'=>188],
['name'=>'TARUCACHI','provincia_id'=>191],
['name'=>'HEROES ALBARRACIN','provincia_id'=>191],
['name'=>'ESTIQUE','provincia_id'=>191],
['name'=>'TICACO','provincia_id'=>191],
['name'=>'TARATA','provincia_id'=>191],
['name'=>'ESTIQUE-PAMPA','provincia_id'=>191],
['name'=>'SITAJARA','provincia_id'=>191],
['name'=>'SUSAPAYA','provincia_id'=>191],
['name'=>'CANOAS DE PUNTA SAL','provincia_id'=>193],
['name'=>'CASITAS','provincia_id'=>193],
['name'=>'ZORRITOS','provincia_id'=>193],
['name'=>'CORRALES','provincia_id'=>192],
['name'=>'LA CRUZ','provincia_id'=>192],
['name'=>'PAMPAS DE HOSPITAL','provincia_id'=>192],
['name'=>'SAN JUAN DE LA VIRGEN','provincia_id'=>192],
['name'=>'TUMBES','provincia_id'=>192],
['name'=>'SAN JACINTO','provincia_id'=>192],
['name'=>'ZARUMILLA','provincia_id'=>194],
['name'=>'MATAPALO','provincia_id'=>194],
['name'=>'AGUAS VERDES','provincia_id'=>194],
['name'=>'PAPAYAL','provincia_id'=>194],
['name'=>'SEPAHUA','provincia_id'=>196],
['name'=>'YURUA','provincia_id'=>196],
['name'=>'RAYMONDI','provincia_id'=>196],
['name'=>'TAHUANIA','provincia_id'=>196],
['name'=>'IPARIA','provincia_id'=>195],
['name'=>'MASISEA','provincia_id'=>195],
['name'=>'MANANTAY','provincia_id'=>195],
['name'=>'CALLERIA','provincia_id'=>195],
['name'=>'CAMPOVERDE','provincia_id'=>195],
['name'=>'NUEVA REQUENA','provincia_id'=>195],
['name'=>'YARINACOCHA','provincia_id'=>195],
['name'=>'ALEXANDER VON HUMBOLDT','provincia_id'=>197],
['name'=>'IRAZOLA','provincia_id'=>197],
['name'=>'NESHUYA','provincia_id'=>197],
['name'=>'PADRE ABAD','provincia_id'=>197],
['name'=>'CURIMANA','provincia_id'=>197],
['name'=>'PURUS','provincia_id'=>198],
['name'=>'LA PUNTA','provincia_id'=>199],
['name'=>'VENTANILLA','provincia_id'=>199],
['name'=>'CARMEN DE LA LEGUA REYNOSO','provincia_id'=>199],
['name'=>'CALLAO','provincia_id'=>199],
['name'=>'BELLAVISTA','provincia_id'=>199],
['name'=>'MI PERU','provincia_id'=>199],
['name'=>'LA PERLA','provincia_id'=>199],
        ]);
    }
}
